// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Property storage_zeroize_activated_before_next_datamanager -- Pre-Assert and Next-Assert VCs for every schema transition.
//! Each proof fn has an empty body: Verus discharges `requires ==> ensures`
//! via SMT; add proof hints in the body if a VC does not discharge.

#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unused_imports)]

use vstd::prelude::*;

use crate::assertions::*;
use crate::storage_zeroize_activated_before_next_datamanager::assertions::*;
use crate::contracts::*;
use crate::system_state::SystemState;
use crate::write_frames::*;

verus! {

/** VC[1]: Pre-Assert -- trivial: this property does not use WIFI_VM's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_wifi_vm(st: SystemState)
  requires
    true /* START has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[2]: Next-Assert (task) -- START + frames + WIFI_VM postcondition |- after_wifi_vm */
pub proof fn vc_next_assert_task_wifi_vm(pre: SystemState, post: SystemState)
  requires
    true /* START has no assertion */,
    wifi_vm_local_write_frame(pre, post),
    wifi_vm_global_write_frame(pre, post),
  ensures
    true /* after_wifi_vm has no assertion */,
{}

/** VC[3]: Pre-Assert -- trivial: this property does not use WIFI's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_wifi(st: SystemState)
  requires
    true /* after_wifi_vm has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[4]: Next-Assert (task) -- after_wifi_vm + frames + WIFI postcondition |- after_wifi */
pub proof fn vc_next_assert_task_wifi(pre: SystemState, post: SystemState)
  requires
    true /* after_wifi_vm has no assertion */,
    wifi_local_write_frame(pre, post),
    wifi_global_write_frame(pre, post),
  ensures
    true /* after_wifi has no assertion */,
{}

/** VC[5]: Pre-Assert -- trivial: this property does not use DECRYPTOR's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_decryptor(st: SystemState)
  requires
    true /* after_wifi has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[6]: Next-Assert (task) -- after_wifi + frames + DECRYPTOR postcondition |- after_decryptor */
pub proof fn vc_next_assert_task_decryptor(pre: SystemState, post: SystemState)
  requires
    true /* after_wifi has no assertion */,
    decryptor_local_write_frame(pre, post),
    decryptor_global_write_frame(pre, post),
  ensures
    true /* after_decryptor has no assertion */,
{}

/** VC[7]: Pre-Assert -- trivial: this property does not use DATA_MANAGER's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_data_manager_1(st: SystemState)
  requires
    true /* after_decryptor has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[8]: Next-Assert (task) -- after_decryptor + frames + DATA_MANAGER postcondition |- after_data_manager_1 */
pub proof fn vc_next_assert_task_data_manager_1(pre: SystemState, post: SystemState)
  requires
    true /* after_decryptor has no assertion */,
    data_manager_local_write_frame(pre, post),
    data_manager_global_write_frame(pre, post),
  ensures
    true /* after_data_manager_1 has no assertion */,
{}

/** VC[9]: Pre-Assert -- trivial: this property does not use DATA_STORAGE's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_data_storage_1(st: SystemState)
  requires
    true /* after_data_manager_1 has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[10]: Next-Assert (task) -- after_data_manager_1 + frames + DATA_STORAGE postcondition |- after_data_storage_1 */
pub proof fn vc_next_assert_task_data_storage_1(pre: SystemState, post: SystemState)
  requires
    true /* after_data_manager_1 has no assertion */,
    data_storage_local_write_frame(pre, post),
    data_storage_global_write_frame(pre, post),
  ensures
    true /* after_data_storage_1 has no assertion */,
{}

/** VC[11]: Pre-Assert -- trivial: this property does not use FIREWALL's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_firewall(st: SystemState)
  requires
    true /* after_data_storage_1 has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[12]: Next-Assert (task) -- after_data_storage_1 + frames + FIREWALL postcondition |- after_firewall */
pub proof fn vc_next_assert_task_firewall(pre: SystemState, post: SystemState)
  requires
    true /* after_data_storage_1 has no assertion */,
    firewall_local_write_frame(pre, post),
    firewall_global_write_frame(pre, post),
  ensures
    true /* after_firewall has no assertion */,
{}

/** VC[13]: Pre-Assert -- trivial: this property does not use DATA_ANALYSIS's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_data_analysis_1(st: SystemState)
  requires
    true /* after_firewall has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[14]: Next-Assert (task) -- after_firewall + frames + DATA_ANALYSIS postcondition |- after_data_analysis_1 */
pub proof fn vc_next_assert_task_data_analysis_1(pre: SystemState, post: SystemState)
  requires
    true /* after_firewall has no assertion */,
    data_analysis_local_write_frame(pre, post),
    data_analysis_global_write_frame(pre, post),
  ensures
    true /* after_data_analysis_1 has no assertion */,
{}

/** VC[15]: Pre-Assert -- trivial: this property does not use DATA_MANAGER's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_data_manager_2(st: SystemState)
  requires
    true /* after_data_analysis_1 has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[16]: Next-Assert (task) -- after_data_analysis_1 + frames + DATA_MANAGER postcondition |- after_data_manager_2 */
pub proof fn vc_next_assert_task_data_manager_2(pre: SystemState, post: SystemState)
  requires
    true /* after_data_analysis_1 has no assertion */,
    data_manager_local_write_frame(pre, post),
    data_manager_global_write_frame(pre, post),
  ensures
    true /* after_data_manager_2 has no assertion */,
{}

/** VC[17]: Pre-Assert -- trivial: this property does not use DATA_STORAGE's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_data_storage_2(st: SystemState)
  requires
    true /* after_data_manager_2 has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[18]: Next-Assert (task) -- after_data_manager_2 + frames + DATA_STORAGE postcondition |- after_data_storage_2 */
pub proof fn vc_next_assert_task_data_storage_2(pre: SystemState, post: SystemState)
  requires
    true /* after_data_manager_2 has no assertion */,
    data_storage_local_write_frame(pre, post),
    data_storage_global_write_frame(pre, post),
  ensures
    true /* after_data_storage_2 has no assertion */,
{}

/** VC[19]: Pre-Assert -- after_data_storage_2 |- LOG_MONITOR compute assumes */
pub proof fn vc_pre_assert_log_monitor(st: SystemState)
  requires
    true /* after_data_storage_2 has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[20]: Next-Assert (task) -- after_data_storage_2 + frames + LOG_MONITOR postcondition |- after_log_monitor */
pub proof fn vc_next_assert_task_log_monitor(pre: SystemState, post: SystemState)
  requires
    true /* after_data_storage_2 has no assertion */,
    log_monitor_local_write_frame(pre, post),
    log_monitor_global_write_frame(pre, post),
    log_monitor::compute_spec_is_valid_variable_guarantee(pre.log_monitor_since_result, post.log_is_valid, pre.data_manager_request, pre.data_manager_response),
    log_monitor::compute_spec_since_result_variable_guarantee(pre.log_monitor_since_result, post.log_monitor_since_result, pre.data_manager_request, pre.data_manager_response),
    log_monitor::compute_spec_historically_no_alert_cmd_variable_guarantee(pre.log_historically_no_alert, post.log_historically_no_alert, post.log_alert),
    log_monitor::compute_spec_Send_Alert_guarantee(post.log_is_valid, pre.data_manager_response, post.log_alert, post.storage_alert),
    log_monitor::compute_spec_Forward_Response_guarantee(post.log_historically_no_alert, pre.data_manager_response, post.log_response_out),
  ensures
    sys_assert_storage_zeroize_activated_before_next_datamanager_after_log_monitor(post),
{}

/** VC[21]: Pre-Assert -- after_log_monitor |- DATA_STORAGE compute assumes */
pub proof fn vc_pre_assert_data_storage_3(st: SystemState)
  requires
    sys_assert_storage_zeroize_activated_before_next_datamanager_after_log_monitor(st),
  ensures
    true /* no assertions at out-places */,
{}

/** VC[22]: Next-Assert (task) -- after_log_monitor + frames + DATA_STORAGE postcondition |- after_data_storage_3 */
pub proof fn vc_next_assert_task_data_storage_3(pre: SystemState, post: SystemState)
  requires
    sys_assert_storage_zeroize_activated_before_next_datamanager_after_log_monitor(pre),
    data_storage_local_write_frame(pre, post),
    data_storage_global_write_frame(pre, post),
    data_storage::compute_spec_zeroize_cmd_variable_guarantee(pre.data_storage_zeroize_cmd, post.data_storage_zeroize_cmd, pre.storage_alert),
    data_storage::compute_spec_Zeroize_Cache_guarantee(post.data_storage_cache, post.data_storage_zeroize_cmd),
  ensures
    sys_assert_storage_zeroize_activated_before_next_datamanager_after_data_storage_3(post),
{}

/** VC[23]: Pre-Assert -- trivial: this property does not use DATA_MANAGER's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_data_manager_3(st: SystemState)
  requires
    sys_assert_storage_zeroize_activated_before_next_datamanager_after_data_storage_3(st),
  ensures
    true /* no assertions at out-places */,
{}

/** VC[24]: Next-Assert (task) -- after_data_storage_3 + frames + DATA_MANAGER postcondition |- after_data_manager_3 */
pub proof fn vc_next_assert_task_data_manager_3(pre: SystemState, post: SystemState)
  requires
    sys_assert_storage_zeroize_activated_before_next_datamanager_after_data_storage_3(pre),
    data_manager_local_write_frame(pre, post),
    data_manager_global_write_frame(pre, post),
  ensures
    true /* after_data_manager_3 has no assertion */,
{}

/** VC[25]: Pre-Assert -- trivial: this property does not use DATA_ANALYSIS's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_data_analysis_2(st: SystemState)
  requires
    true /* after_data_manager_3 has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[26]: Next-Assert (task) -- after_data_manager_3 + frames + DATA_ANALYSIS postcondition |- after_data_analysis_2 */
pub proof fn vc_next_assert_task_data_analysis_2(pre: SystemState, post: SystemState)
  requires
    true /* after_data_manager_3 has no assertion */,
    data_analysis_local_write_frame(pre, post),
    data_analysis_global_write_frame(pre, post),
  ensures
    true /* after_data_analysis_2 has no assertion */,
{}

/** VC[27]: Pre-Assert -- trivial: this property does not use ENCRYPTOR's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_encryptor(st: SystemState)
  requires
    true /* after_data_analysis_2 has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[28]: Next-Assert (task) -- after_data_analysis_2 + frames + ENCRYPTOR postcondition |- after_encryptor */
pub proof fn vc_next_assert_task_encryptor(pre: SystemState, post: SystemState)
  requires
    true /* after_data_analysis_2 has no assertion */,
    encryptor_local_write_frame(pre, post),
    encryptor_global_write_frame(pre, post),
  ensures
    true /* after_encryptor has no assertion */,
{}

/** VC[29]: Pre-Assert -- trivial: this property does not use REPORT_MONITOR's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_report_monitor(st: SystemState)
  requires
    true /* after_encryptor has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[30]: Next-Assert (task) -- after_encryptor + frames + REPORT_MONITOR postcondition |- after_report_monitor */
pub proof fn vc_next_assert_task_report_monitor(pre: SystemState, post: SystemState)
  requires
    true /* after_encryptor has no assertion */,
    report_monitor_local_write_frame(pre, post),
    report_monitor_global_write_frame(pre, post),
  ensures
    true /* after_report_monitor has no assertion */,
{}

/** VC[31]: Next-Assert (control point) -- after_report_monitor |- END (state unchanged) */
pub proof fn vc_next_assert_skip_t15(st: SystemState)
  requires
    true /* after_report_monitor has no assertion */,
  ensures
    true /* END has no assertion */,
{}

} // verus!
