// Do not edit this file as it will be overwritten if codegen is rerun

use data::*;

use proptest::prelude::*;

pub fn option_strategy_default
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (base: S) -> impl Strategy<Value = Option<T>>
{
  option_strategy_bias(1, base)
}

pub fn option_strategy_bias
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (
  bias: u32,
  base: S) -> impl Strategy<Value = Option<T>>
{
  prop_oneof![
    bias => base.prop_map(Some),
    1 => Just(None),
  ]
}

pub fn Common_DummyMessage_Impl_strategy_default() -> impl Strategy<Value = Common::DummyMessage_Impl>
{
  Common_DummyMessage_Impl_strategy_cust(any::<u8>())
}

pub fn Common_DummyMessage_Impl_strategy_cust<u8_strategy: Strategy<Value = u8>> (base_strategy: u8_strategy) -> impl Strategy<Value = Common::DummyMessage_Impl>
{
  proptest::collection::vec(base_strategy, Common::Common_DummyMessage_Impl_DIM_0)
    .prop_map(|v| {
      let boxed: Box<[u8; Common::Common_DummyMessage_Impl_DIM_0]> = v.into_boxed_slice().try_into().unwrap();
      *boxed
  })
}

pub fn Common_ip_address_strategy_default() -> impl Strategy<Value = Common::ip_address>
{
  Common_ip_address_strategy_cust(any::<u8>())
}

pub fn Common_ip_address_strategy_cust<u8_strategy: Strategy<Value = u8>> (base_strategy: u8_strategy) -> impl Strategy<Value = Common::ip_address>
{
  proptest::collection::vec(base_strategy, Common::Common_ip_address_DIM_0)
    .prop_map(|v| {
      let boxed: Box<[u8; Common::Common_ip_address_DIM_0]> = v.into_boxed_slice().try_into().unwrap();
      *boxed
  })
}

pub fn Common_encryptedPayload_Impl_strategy_default() -> impl Strategy<Value = Common::encryptedPayload_Impl>
{
  Common_encryptedPayload_Impl_strategy_cust(any::<u8>())
}

pub fn Common_encryptedPayload_Impl_strategy_cust<u8_strategy: Strategy<Value = u8>> (base_strategy: u8_strategy) -> impl Strategy<Value = Common::encryptedPayload_Impl>
{
  proptest::collection::vec(base_strategy, Common::Common_encryptedPayload_Impl_DIM_0)
    .prop_map(|v| {
      let boxed: Box<[u8; Common::Common_encryptedPayload_Impl_DIM_0]> = v.into_boxed_slice().try_into().unwrap();
      *boxed
  })
}

pub fn Common_MsgHeader_Impl_strategy_default() -> impl Strategy<Value = Common::MsgHeader_Impl>
{
  Common_MsgHeader_Impl_strategy_cust(
    any::<u32>(),
    any::<u32>()
  )
}

pub fn Common_MsgHeader_Impl_strategy_cust
  <src_u32_strategy: Strategy<Value = u32>, 
   dst_u32_strategy: Strategy<Value = u32>> (
  src_strategy: src_u32_strategy,
  dst_strategy: dst_u32_strategy) -> impl Strategy<Value = Common::MsgHeader_Impl>
{
  (src_strategy, dst_strategy).prop_map(|(src, dst)| {
    Common::MsgHeader_Impl { src, dst }
  })
}

pub fn MATRICS_Model_Transformations_AllowList_Impl_strategy_default() -> impl Strategy<Value = MATRICS_Model_Transformations::AllowList_Impl>
{
  MATRICS_Model_Transformations_AllowList_Impl_strategy_cust(any::<u32>())
}

pub fn MATRICS_Model_Transformations_AllowList_Impl_strategy_cust<u32_strategy: Strategy<Value = u32>> (base_strategy: u32_strategy) -> impl Strategy<Value = MATRICS_Model_Transformations::AllowList_Impl>
{
  proptest::collection::vec(base_strategy, MATRICS_Model_Transformations::MATRICS_Model_Transformations_AllowList_Impl_DIM_0)
    .prop_map(|v| {
      let boxed: Box<[u32; MATRICS_Model_Transformations::MATRICS_Model_Transformations_AllowList_Impl_DIM_0]> = v.into_boxed_slice().try_into().unwrap();
      *boxed
  })
}

pub fn Common_Log_Impl_strategy_default() -> impl Strategy<Value = Common::Log_Impl>
{
  Common_Log_Impl_strategy_cust(
    any::<u32>(),
    any::<u32>(),
    any::<u32>(),
    any::<u32>(),
    any::<i32>(),
    any::<i32>(),
    any::<i32>()
  )
}

pub fn Common_Log_Impl_strategy_cust
  <timestamp_u32_strategy: Strategy<Value = u32>, 
   userID_u32_strategy: Strategy<Value = u32>, 
   numSuspects_u32_strategy: Strategy<Value = u32>, 
   numSuspectsFlagged_u32_strategy: Strategy<Value = u32>, 
   yaw_i32_strategy: Strategy<Value = i32>, 
   pitch_i32_strategy: Strategy<Value = i32>, 
   roll_i32_strategy: Strategy<Value = i32>> (
  timestamp_strategy: timestamp_u32_strategy,
  userID_strategy: userID_u32_strategy,
  numSuspects_strategy: numSuspects_u32_strategy,
  numSuspectsFlagged_strategy: numSuspectsFlagged_u32_strategy,
  yaw_strategy: yaw_i32_strategy,
  pitch_strategy: pitch_i32_strategy,
  roll_strategy: roll_i32_strategy) -> impl Strategy<Value = Common::Log_Impl>
{
  (timestamp_strategy, userID_strategy, numSuspects_strategy, numSuspectsFlagged_strategy, yaw_strategy, pitch_strategy, roll_strategy).prop_map(|(timestamp, userID, numSuspects, numSuspectsFlagged, yaw, pitch, roll)| {
    Common::Log_Impl { timestamp, userID, numSuspects, numSuspectsFlagged, yaw, pitch, roll }
  })
}

pub fn Common_Request_Impl_strategy_default() -> impl Strategy<Value = Common::Request_Impl>
{
  Common_Request_Impl_strategy_cust(
    any::<i32>(),
    any::<i32>(),
    any::<i32>(),
    any::<i32>(),
    any::<i32>()
  )
}

pub fn Common_Request_Impl_strategy_cust
  <requestID_i32_strategy: Strategy<Value = i32>, 
   analysisType_i32_strategy: Strategy<Value = i32>, 
   userID_i32_strategy: Strategy<Value = i32>, 
   startTime_i32_strategy: Strategy<Value = i32>, 
   endTime_i32_strategy: Strategy<Value = i32>> (
  requestID_strategy: requestID_i32_strategy,
  analysisType_strategy: analysisType_i32_strategy,
  userID_strategy: userID_i32_strategy,
  startTime_strategy: startTime_i32_strategy,
  endTime_strategy: endTime_i32_strategy) -> impl Strategy<Value = Common::Request_Impl>
{
  (requestID_strategy, analysisType_strategy, userID_strategy, startTime_strategy, endTime_strategy).prop_map(|(requestID, analysisType, userID, startTime, endTime)| {
    Common::Request_Impl { requestID, analysisType, userID, startTime, endTime }
  })
}

pub fn Common_ResponseHeader_Impl_strategy_default() -> impl Strategy<Value = Common::ResponseHeader_Impl>
{
  Common_ResponseHeader_Impl_strategy_cust(
    any::<i32>(),
    any::<i32>(),
    any::<i32>()
  )
}

pub fn Common_ResponseHeader_Impl_strategy_cust
  <requestID_i32_strategy: Strategy<Value = i32>, 
   sequenceNumber_i32_strategy: Strategy<Value = i32>, 
   totalParts_i32_strategy: Strategy<Value = i32>> (
  requestID_strategy: requestID_i32_strategy,
  sequenceNumber_strategy: sequenceNumber_i32_strategy,
  totalParts_strategy: totalParts_i32_strategy) -> impl Strategy<Value = Common::ResponseHeader_Impl>
{
  (requestID_strategy, sequenceNumber_strategy, totalParts_strategy).prop_map(|(requestID, sequenceNumber, totalParts)| {
    Common::ResponseHeader_Impl { requestID, sequenceNumber, totalParts }
  })
}

pub fn Common_shortText_strategy_default() -> impl Strategy<Value = Common::shortText>
{
  Common_shortText_strategy_cust(any::<u8>())
}

pub fn Common_shortText_strategy_cust<u8_strategy: Strategy<Value = u8>> (base_strategy: u8_strategy) -> impl Strategy<Value = Common::shortText>
{
  proptest::collection::vec(base_strategy, Common::Common_shortText_DIM_0)
    .prop_map(|v| {
      let boxed: Box<[u8; Common::Common_shortText_DIM_0]> = v.into_boxed_slice().try_into().unwrap();
      *boxed
  })
}

pub fn Common_AnalysisReport_Impl_strategy_default() -> impl Strategy<Value = Common::AnalysisReport_Impl>
{
  Common_AnalysisReport_Impl_strategy_cust(
    Common_MsgHeader_Impl_strategy_default(),
    any::<u8>()
  )
}

pub fn Common_AnalysisReport_Impl_strategy_cust
  <header_Common_MsgHeader_Impl_strategy: Strategy<Value = Common::MsgHeader_Impl>, 
   payload_u8_strategy: Strategy<Value = u8>> (
  header_strategy: header_Common_MsgHeader_Impl_strategy,
  payload_strategy: payload_u8_strategy) -> impl Strategy<Value = Common::AnalysisReport_Impl>
{
  (header_strategy, payload_strategy).prop_map(|(header, payload)| {
    Common::AnalysisReport_Impl { header, payload }
  })
}

pub fn Common_LogArray_Impl_strategy_default() -> impl Strategy<Value = Common::LogArray_Impl>
{
  Common_LogArray_Impl_strategy_cust(Common_Log_Impl_strategy_default())
}

pub fn Common_LogArray_Impl_strategy_cust<Common_Log_Impl_strategy: Strategy<Value = Common::Log_Impl>> (base_strategy: Common_Log_Impl_strategy) -> impl Strategy<Value = Common::LogArray_Impl>
{
  proptest::collection::vec(base_strategy, Common::Common_LogArray_Impl_DIM_0)
    .prop_map(|v| {
      let boxed: Box<[Common::Log_Impl; Common::Common_LogArray_Impl_DIM_0]> = v.into_boxed_slice().try_into().unwrap();
      *boxed
  })
}

pub fn Common_AnalysisRequest_Impl_strategy_default() -> impl Strategy<Value = Common::AnalysisRequest_Impl>
{
  Common_AnalysisRequest_Impl_strategy_cust(
    Common_MsgHeader_Impl_strategy_default(),
    Common_Request_Impl_strategy_default()
  )
}

pub fn Common_AnalysisRequest_Impl_strategy_cust
  <header_Common_MsgHeader_Impl_strategy: Strategy<Value = Common::MsgHeader_Impl>, 
   payload_Common_Request_Impl_strategy: Strategy<Value = Common::Request_Impl>> (
  header_strategy: header_Common_MsgHeader_Impl_strategy,
  payload_strategy: payload_Common_Request_Impl_strategy) -> impl Strategy<Value = Common::AnalysisRequest_Impl>
{
  (header_strategy, payload_strategy).prop_map(|(header, payload)| {
    Common::AnalysisRequest_Impl { header, payload }
  })
}

pub fn Common_WifiHeader_Impl_strategy_default() -> impl Strategy<Value = Common::WifiHeader_Impl>
{
  Common_WifiHeader_Impl_strategy_cust(
    Common_shortText_strategy_default(),
    Common_shortText_strategy_default(),
    any::<u32>(),
    Common_shortText_strategy_default(),
    Common_ip_address_strategy_default(),
    Common_ip_address_strategy_default()
  )
}

pub fn Common_WifiHeader_Impl_strategy_cust
  <Host_Common_shortText_strategy: Strategy<Value = Common::shortText>, 
   UserAgent_Common_shortText_strategy: Strategy<Value = Common::shortText>, 
   ContentLength_u32_strategy: Strategy<Value = u32>, 
   XForwardedProto_Common_shortText_strategy: Strategy<Value = Common::shortText>, 
   XForwardedFor_Common_ip_address_strategy: Strategy<Value = Common::ip_address>, 
   XRealIP_Common_ip_address_strategy: Strategy<Value = Common::ip_address>> (
  Host_strategy: Host_Common_shortText_strategy,
  UserAgent_strategy: UserAgent_Common_shortText_strategy,
  ContentLength_strategy: ContentLength_u32_strategy,
  XForwardedProto_strategy: XForwardedProto_Common_shortText_strategy,
  XForwardedFor_strategy: XForwardedFor_Common_ip_address_strategy,
  XRealIP_strategy: XRealIP_Common_ip_address_strategy) -> impl Strategy<Value = Common::WifiHeader_Impl>
{
  (Host_strategy, UserAgent_strategy, ContentLength_strategy, XForwardedProto_strategy, XForwardedFor_strategy, XRealIP_strategy).prop_map(|(Host, UserAgent, ContentLength, XForwardedProto, XForwardedFor, XRealIP)| {
    Common::WifiHeader_Impl { Host, UserAgent, ContentLength, XForwardedProto, XForwardedFor, XRealIP }
  })
}

pub fn Common_ResponseLog_Impl_strategy_default() -> impl Strategy<Value = Common::ResponseLog_Impl>
{
  Common_ResponseLog_Impl_strategy_cust(
    Common_ResponseHeader_Impl_strategy_default(),
    Common_LogArray_Impl_strategy_default()
  )
}

pub fn Common_ResponseLog_Impl_strategy_cust
  <header_Common_ResponseHeader_Impl_strategy: Strategy<Value = Common::ResponseHeader_Impl>, 
   payload_Common_LogArray_Impl_strategy: Strategy<Value = Common::LogArray_Impl>> (
  header_strategy: header_Common_ResponseHeader_Impl_strategy,
  payload_strategy: payload_Common_LogArray_Impl_strategy) -> impl Strategy<Value = Common::ResponseLog_Impl>
{
  (header_strategy, payload_strategy).prop_map(|(header, payload)| {
    Common::ResponseLog_Impl { header, payload }
  })
}

pub fn Common_IncomingWifiMessage_Impl_strategy_default() -> impl Strategy<Value = Common::IncomingWifiMessage_Impl>
{
  Common_IncomingWifiMessage_Impl_strategy_cust(
    Common_WifiHeader_Impl_strategy_default(),
    Common_encryptedPayload_Impl_strategy_default()
  )
}

pub fn Common_IncomingWifiMessage_Impl_strategy_cust
  <header_Common_WifiHeader_Impl_strategy: Strategy<Value = Common::WifiHeader_Impl>, 
   payload_Common_encryptedPayload_Impl_strategy: Strategy<Value = Common::encryptedPayload_Impl>> (
  header_strategy: header_Common_WifiHeader_Impl_strategy,
  payload_strategy: payload_Common_encryptedPayload_Impl_strategy) -> impl Strategy<Value = Common::IncomingWifiMessage_Impl>
{
  (header_strategy, payload_strategy).prop_map(|(header, payload)| {
    Common::IncomingWifiMessage_Impl { header, payload }
  })
}
