#pragma once

#include <printf.h>
#include <util.h>
#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if codegen is rerun


bool response_log_in_is_empty(void);
bool get_response_log_in_poll(sb_event_counter_t *numDropped, Common_ResponseLog_Impl *data);
bool get_response_log_in(Common_ResponseLog_Impl *data);
bool request_log_is_empty(void);
bool get_request_log_poll(sb_event_counter_t *numDropped, Common_Request_Impl *data);
bool get_request_log(Common_Request_Impl *data);
bool put_response_log_out(const Common_ResponseLog_Impl *data);
bool put_alert();
