// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {

  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct OutgoingWifiMessage_Impl {
    pub header: MsgHeader_Impl,
    pub payload: OutgoingPayload_Impl
  }

  impl Default for OutgoingWifiMessage_Impl {
    fn default() -> Self
    {
      Self { header: Common::MsgHeader_Impl::default(), payload: [0; Common::Common_OutgoingPayload_Impl_DIM_0] }
    }
  }

}