#!/bin/sh

echo "Setting the date"

date -s "2026-01-01 00:00:00"

echo "Configuring self-signed certificates"

openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
-keyout /etc/ssl/private/nginx-selfsigned.key \
-out /etc/ssl/certs/nginx-selfsigned.crt \
-config /etc/nginx/server.cnf \
-extensions v3_req