#pragma once

#if __has_include(<libvmm/util/util.h>)
#include <libvmm/util/util.h>
#elif __has_include(<sddf/util/util.h>)
#include <sddf/util/printf.h>
#include <sddf/util/util.h>
#define printf sddf_dprintf
#else
#include <printf.h>
#endif

#include <stddef.h>

// These match musl's prototypes, so re-declaring them is harmless where sddf's
// custom libc is on the include path too.
void *memcpy(void *restrict dest, const void *restrict src, size_t n);
void *memset(void *dest, int c, size_t n);

#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun


bool response_log_in_is_empty(void);
bool get_response_log_in_poll(sb_event_counter_t *numDropped, Common_AnalysisResponse_Impl *data);
bool get_response_log_in(Common_AnalysisResponse_Impl *data);
bool peek_response_log_in(Common_AnalysisResponse_Impl *data);
bool request_log_is_empty(void);
bool get_request_log_poll(sb_event_counter_t *numDropped, Common_AnalysisRequest_Impl *data);
bool get_request_log(Common_AnalysisRequest_Impl *data);
bool peek_request_log(Common_AnalysisRequest_Impl *data);
bool put_response_log_out(const Common_AnalysisResponse_Impl *data);
bool peek_response_log_out(Common_AnalysisResponse_Impl *data);
bool put_alert_out();
bool peek_alert_out();
bool put_storage_alert_out();
bool peek_storage_alert_out();
