// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {

  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct EncryptedResponse_Impl {
    pub request: Request_Impl,
    pub validLogCount: u32,
    pub moreAvailable: bool,
    pub nextStartTime: u64,
    pub logs: EncryptedResponseLog_Impl,
  }

  impl Default for EncryptedResponse_Impl {
    fn default() -> Self
    {
      Self { request: Common::Request_Impl::default(), validLogCount: 0, moreAvailable: false, nextStartTime: 0, logs: [Common::StoredLogFile_Impl::default(); Common::Common_EncryptedResponseLog_Impl_DIM_0] }
    }
  }

}