// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {

  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct LogFileMetadata_Impl {
    pub guardID: u32,
    pub deviceID: u32,
    pub timestamp: u64,
  }

  impl Default for LogFileMetadata_Impl {
    fn default() -> Self
    {
      Self { guardID: 0, deviceID: 0, timestamp: 0 }
    }
  }

}