// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {

  pub const Common_Nonce_Impl_BYTE_SIZE: usize = 12;
  pub const Common_Nonce_Impl_DIM_0: usize = 12;

  pub type Nonce_Impl = [u8; Common_Nonce_Impl_DIM_0];

}