// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {

  pub const Common_ResponseLog_Impl_BYTE_SIZE: usize = 3520;
  pub const Common_ResponseLog_Impl_DIM_0: usize = 10;

  pub type ResponseLog_Impl = [Log_Impl; Common_ResponseLog_Impl_DIM_0];

}