// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {

  pub const Common_shortText_BYTE_SIZE: usize = 64;
  pub const Common_shortText_DIM_0: usize = 64;

  pub type shortText = [u8; Common_shortText_DIM_0];

}