// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {

  #[repr(C)]
  #[derive(Copy, Clone, Debug, PartialEq, Eq)]
  pub enum TargetAssessment {
    pub Unreviewed = 0,
    pub Safe = 1,
    pub Threat = 2,
  }

  impl Default for TargetAssessment {
    fn default() -> Self
    {
      TargetAssessment::Unreviewed
    }
  }

}