ARG MICROKIT_SDK_VER=2.2.0

FROM --platform=linux/arm64 ubuntu:24.04 AS builder

ARG MICROKIT_SDK_VER
ARG RUST_TOOLCHAIN_VER=1.92.0
ARG RUST_NIGHTLY_VER=nightly-2026-01-25
ARG SDFGEN_VER=0.30.1
ARG VERUS_VER=0.2026.01.23.1650a05
ARG Z3_VER=z3-4.12.5

ENV USER=microkit

RUN apt-get update && apt install -y sudo && \
  rm -rf /var/lib/apt/lists/* && \
  useradd -m -s /bin/bash -N ${USER} && \
  usermod -s /bin/bash ${USER} && \
  echo "${USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers && \
  chmod 0440 /etc/sudoers && \
  chmod g+w /etc/passwd

USER ${USER}
ENV HOME=/home/microkit
ENV PROVERS_DIR=${HOME}/provers
ENV LIONSOS=${PROVERS_DIR}/lionsos
ENV SIREUM_HOME=${PROVERS_DIR}/Sireum
ENV VERUS_DIR=${PROVERS_DIR}/verus
ENV PATH=${VERUS_DIR}:${SIREUM_HOME}/bin:${PROVERS_DIR}/sdfgen-venv/bin:${HOME}/.cargo/bin:$PATH
WORKDIR ${HOME}
SHELL ["/bin/bash", "-c"]

RUN echo "ARM: Install build and runtime dependencies in one layer for caching" && \
  sudo apt-get update && \
  sudo apt-get install -y \
    software-properties-common \
    binutils build-essential \
    clang llvm lld device-tree-compiler \
    libxml2-utils \
    curl wget git unzip \
    python3.12 python3-pip python3.12-venv \
    qemu-system-arm qemu-system-misc \
    gcc-riscv64-unknown-elf \
    cmake pandoc ninja-build \
    texlive-latex-base texlive-latex-recommended \
    texlive-fonts-recommended texlive-fonts-extra && \
  sudo rm -rf /var/lib/apt/lists/*

RUN echo "ARM: Installing Rust - Verus ${VERUS_VER} requires ${RUST_TOOLCHAIN_VER}" && \
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
  . ${HOME}/.cargo/env && \
  rustup toolchain install ${RUST_TOOLCHAIN_VER}-aarch64-unknown-linux-gnu && \
  rustup component add rust-src --toolchain ${RUST_TOOLCHAIN_VER}-aarch64-unknown-linux-gnu && \
  rustup toolchain install ${RUST_NIGHTLY_VER} --component rustfmt,rust-src,rustc-dev,llvm-tools-preview,rust-analyzer

#https://verus-lang.zulipchat.com/#narrow/channel/399078-help/topic/.E2.9C.94.20Verus.20support.20for.20arm64.20on.20linux.3F/near/561282380
RUN echo "ARM: Build Z3 for Linux ARM - Verus requires ${Z3_VER} which requires building from source" && \
  mkdir -p ${PROVERS_DIR} && \
  git clone https://github.com/Z3Prover/z3.git ${PROVERS_DIR}/z3-build && \
  cd ${PROVERS_DIR}/z3-build && git checkout ${Z3_VER} && \
  python3.12 scripts/mk_make.py && cd build/ && make && \
  make -C ${PROVERS_DIR}/z3-build/build install DESTDIR=${PROVERS_DIR}/ PREFIX=z3 && \
  cd ${PROVERS_DIR} && rm -rf ${PROVERS_DIR}/z3-build

RUN echo "ARM: Installing Verus Linux ARM ${VERUS_VER} - Verus doesn't release Linux ARM64 assets so need to build it from source" && \
  cd ${PROVERS_DIR} && source ${HOME}/.cargo/env && \
  git clone https://github.com/verus-lang/verus.git verus-build && \
  cd verus-build/source && git checkout release/${VERUS_VER} && \
  ln -s ${PROVERS_DIR}/z3/bin/z3 ./z3 && \
  source ../tools/activate && vargo build --release && \
  cp -r ./target-verus/release ${VERUS_DIR} && \
  cd ${PROVERS_DIR} && rm -rf ${PROVERS_DIR}/verus-build

RUN echo "ARM: Install Microkit SDK and LionsOS. sdfgen for Linux ARM is not provided on PyPI so need to build it from source which requires zig 0.15.2" && \
  cd ${PROVERS_DIR} && \
  wget https://ziglang.org/download/0.15.2/zig-aarch64-linux-0.15.2.tar.xz && \
  tar xvf zig-aarch64-linux-0.15.2.tar.xz && \
  export PATH=${PROVERS_DIR}/zig-aarch64-linux-0.15.2:$PATH && \
  python3.12 -m venv ${PROVERS_DIR}/sdfgen-venv && \
  git clone https://github.com/au-ts/microkit_sdf_gen.git && \
  cd microkit_sdf_gen && git checkout ${SDFGEN_VER} && \
  ${PROVERS_DIR}/sdfgen-venv/bin/pip install . && \
  cd ${PROVERS_DIR} && \
  wget https://github.com/seL4/microkit/releases/download/${MICROKIT_SDK_VER}/microkit-sdk-${MICROKIT_SDK_VER}-linux-aarch64.tar.gz && \
  tar xvf ${PROVERS_DIR}/microkit-sdk-${MICROKIT_SDK_VER}-linux-aarch64.tar.gz && \
  git clone --rec --depth=1 --shallow-submodules https://github.com/au-ts/lionsos.git ${LIONSOS} && \
  rm -rf ${PROVERS_DIR}/lionsos/dep/micropython ${PROVERS_DIR}/lionsos/dep/wasm-micro-runtime \
    ${PROVERS_DIR}/lionsos/examples ${PROVERS_DIR}/lionsos/.git \
    ${PROVERS_DIR}/*tar.gz ${PROVERS_DIR}/zig* ${PROVERS_DIR}/microkit_sdf_gen

RUN echo "ARM: Building Microkit SDK 1.4.1 with domain scheduling" && \
  cd ${PROVERS_DIR} && . ${HOME}/.cargo/env && \
  export MICROKIT_1_4_1_SDK_DIR=${PROVERS_DIR}/microkit-sdk-1.4.1 && \
  export MICROKIT_1_4_1_BUILD_DIR=${PROVERS_DIR}/microkit-sdk-1.4.1-build && \
  mkdir -p ${MICROKIT_1_4_1_BUILD_DIR} && cd ${MICROKIT_1_4_1_BUILD_DIR} && \
  rustup target add x86_64-unknown-linux-musl && rustup target add aarch64-unknown-linux-musl && \
  wget -O aarch64-toolchain.tar.gz https://developer.arm.com/-/media/files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-aarch64-aarch64-none-elf.tar.xz && \
  tar xf ${MICROKIT_1_4_1_BUILD_DIR}/aarch64-toolchain.tar.gz && rm ${MICROKIT_1_4_1_BUILD_DIR}/aarch64-toolchain.tar.gz && \
  export PATH=${MICROKIT_1_4_1_BUILD_DIR}/arm-gnu-toolchain-12.2.rel1-aarch64-aarch64-none-elf/bin:${PATH}:. && \
  git clone https://github.com/Ivan-Velickovic/seL4 --branch microkit_domains && \
  git clone https://github.com/JE-Archer/microkit --branch domains && cd microkit && \
  python3.12 -m venv pyenv && \
  ./pyenv/bin/pip install --upgrade pip setuptools wheel && \
  ./pyenv/bin/pip install -r requirements.txt && \
  ./pyenv/bin/python build_sdk.py --experimental-domain-support --sel4=${MICROKIT_1_4_1_BUILD_DIR}/seL4 --configs debug \
    --tool-target-triple="aarch64-unknown-linux-musl" && \
  microkit=$(find ${MICROKIT_1_4_1_BUILD_DIR}/microkit/release/ -type d -name microkit-sdk*) && \
  mv ${microkit} ${MICROKIT_1_4_1_SDK_DIR} && \
  cd ${PROVERS_DIR} && rm -rf ${MICROKIT_1_4_1_BUILD_DIR}

RUN echo "ARM: Installing a minimal Sireum so that Slash scripts can be run" && \
  export SIREUM_LINUX_BIN=${SIREUM_HOME}/bin/linux/arm && \
  mkdir -p ${SIREUM_HOME}/bin && \
  wget https://raw.githubusercontent.com/sireum/kekinian/refs/heads/master/versions.properties -O ${SIREUM_HOME}/versions.properties && \
  wget https://raw.githubusercontent.com/sireum/kekinian/refs/heads/master/bin/init.sh -O ${SIREUM_HOME}/bin/init.sh && \
  chmod 700 ${SIREUM_HOME}/bin/init.sh && \
  SIREUM_NO_SETUP=true ${SIREUM_HOME}/bin/init.sh && \
  ${SIREUM_HOME}/bin/sireum --init && \
  rm -rf ${SIREUM_HOME}/bin/sbt ${SIREUM_LINUX_BIN}/{.,}cs* ${SIREUM_LINUX_BIN}/{.,}cvc* \
    ${SIREUM_LINUX_BIN}/{.,}checkstack* ${SIREUM_LINUX_BIN}/z3 \
    ${SIREUM_HOME}/lib/jacoco* ${SIREUM_HOME}/lib/marytts_text2wav.jar ${HOME}/Downloads/sireum \
    ${SIREUM_LINUX_BIN}/java/jmods \
    ${SIREUM_LINUX_BIN}/java/lib/src.zip \
    ${SIREUM_LINUX_BIN}/java/include \
    ${SIREUM_LINUX_BIN}/java/man \
    ${SIREUM_LINUX_BIN}/java/demo \
    ${SIREUM_LINUX_BIN}/java/lib/client \
    ${SIREUM_LINUX_BIN}/java/lib/libjfxwebkit.so \
    ${SIREUM_LINUX_BIN}/java/lib/libavplugin-* \
    ${SIREUM_LINUX_BIN}/java/lib/libjavafx_* \
    ${SIREUM_LINUX_BIN}/java/lib/libglass* \
    ${SIREUM_LINUX_BIN}/java/lib/libgstreamer-lite.so \
    ${SIREUM_LINUX_BIN}/java/lib/libprism_* \
    ${SIREUM_LINUX_BIN}/java/lib/libdecora_sse.so \
    ${SIREUM_LINUX_BIN}/java/lib/libfxplugins.so \
    ${SIREUM_LINUX_BIN}/java/lib/javafx-swt.jar \
    ${SIREUM_LINUX_BIN}/java/lib/javafx.properties \
    ${SIREUM_LINUX_BIN}/java/lib/libawt_xawt.so \
    ${SIREUM_LINUX_BIN}/java/lib/libsplashscreen.so



# ---- Final stage: only runtime dependencies ----
FROM --platform=linux/arm64 ubuntu:24.04

ARG MICROKIT_SDK_VER

ENV USER=microkit

RUN echo "ARM: Final Stage - create microkit user" && \
  apt-get update && apt install -y sudo && \
  rm -rf /var/lib/apt/lists/* && \
  useradd -m -s /bin/bash -N ${USER} && \
  usermod -s /bin/bash ${USER} && \
  echo "${USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers && \
  chmod 0440 /etc/sudoers && \
  chmod g+w /etc/passwd

USER ${USER}
ENV HOME=/home/microkit
ENV PROVERS_DIR=${HOME}/provers
ENV LIONSOS=${PROVERS_DIR}/lionsos
ENV VMM_DIR=${LIONSOS}/dep/libvmm
ENV MICROKIT_BOARD=qemu_virt_aarch64
ENV MICROKIT_SDK=${PROVERS_DIR}/microkit-sdk-1.4.1
ENV MICROKIT_SDK_CURRENT=${PROVERS_DIR}/microkit-sdk-${MICROKIT_SDK_VER}
ENV SIREUM_HOME=${PROVERS_DIR}/Sireum
ENV VERUS_Z3_PATH=${PROVERS_DIR}/z3/bin/z3
ENV VERUS_DIR=${PROVERS_DIR}/verus
ENV PATH=${VERUS_DIR}:${SIREUM_HOME}/bin:${PROVERS_DIR}/sdfgen-venv/bin:${HOME}/.cargo/bin:$PATH
WORKDIR ${HOME}

COPY --from=builder --chown=microkit /home/microkit /home/microkit

RUN echo "ARM: Final Stage - install dependencies" && \
  sudo apt-get update && \
  sudo apt-get install -y \
    binutils build-essential \
    clang llvm lld device-tree-compiler \
    curl wget git \
    libxml2-utils \
    python3.12 python3-pip python3.12-venv \
    qemu-system-arm qemu-system-misc && \
  sudo rm -rf /var/lib/apt/lists/* && \
  echo "alias env='env | sort'" >> ${HOME}/.bash_aliases && \
  echo "alias ddir='ls -lFaG'"  >> ${HOME}/.bash_aliases && \
  echo "alias dir='ls -lFG'" >> ${HOME}/.bash_aliases && \
  echo "alias ..='cd ..'" >> ${HOME}/.bash_aliases

#FROM jasonbelt/microkit_provers

WORKDIR /home/microkit/ICS

RUN sudo apt-get update && sudo apt install cpio vim

ENV MICROKIT_SDK=/home/microkit/provers/microkit-sdk-2.2.0

EXPOSE 8080/tcp
EXPOSE 8443/tcp