// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

use proptest::prelude::*;

use super::test_apis::*;

use crate::bridge::cpuSw_reportMonitor_reportMonitor_GUMBOX as GUMBOX;

pub enum HarnessResult {
  RejectedPrecondition,
  FailedPostcondition(TestCaseError),
  Passed,
}

/** Contract-based test harness for the initialize entry point
  */
pub fn testInitializeCB() -> HarnessResult
{
  // [InvokeEntryPoint]: Invoke the entry point
  crate::cpuSw_reportMonitor_reportMonitor_initialize();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let counter = get_counter();
  let is_invalid2 = get_is_invalid2();
  let is_valid1 = get_is_valid1();
  let since_result = get_since_result();
  let api_alert = get_alert();
  let api_analysis_report_out = get_analysis_report_out();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::initialize_IEP_Post (counter, is_invalid2, is_valid1, since_result, api_alert, api_analysis_report_out) {
    return HarnessResult::FailedPostcondition(
      TestCaseError::Fail("Postcondition failed: incorrect output behavior".into())
    );
  }

  return HarnessResult::Passed
}

#[macro_export]
macro_rules!
testInitializeCB_macro {
  (
    $test_name: ident,
    config: $config:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(empty in ::proptest::strategy::Just(())) {
        match $crate::test::util::cb_apis::testInitializeCB() {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            unreachable!("This branch is infeasible")
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param api_analysis_report_in incoming event data port
  * @param api_analysis_request incoming event data port
  */
pub fn testComputeCB(
  api_analysis_report_in: Option<Common::AnalysisReport_Impl>,
  api_analysis_request: Option<Common::AnalysisRequest_Impl>) -> HarnessResult
{
  // Initialize the app
  crate::cpuSw_reportMonitor_reportMonitor_initialize();

  // [SaveInLocal]: retrieve and save the current (input) values of GUMBO-declared local state variables as retrieved
  //                from the component state
  let In_counter: u32 = get_counter();
  let In_is_invalid2: bool = get_is_invalid2();
  let In_is_valid1: bool = get_is_valid1();
  let In_since_result: bool = get_since_result();

  // [PutInPorts]: Set values on the input ports
  put_analysis_report_in(api_analysis_report_in);
  put_analysis_request(api_analysis_request);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::cpuSw_reportMonitor_reportMonitor_timeTriggered();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let counter = get_counter();
  let is_invalid2 = get_is_invalid2();
  let is_valid1 = get_is_valid1();
  let since_result = get_since_result();
  let api_alert = get_alert();
  let api_analysis_report_out = get_analysis_report_out();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::compute_CEP_Post(In_counter, In_is_invalid2, In_is_valid1, In_since_result, counter, is_invalid2, is_valid1, since_result, api_analysis_report_in, api_analysis_request, api_alert, api_analysis_report_out) {
    return HarnessResult::FailedPostcondition(TestCaseError::Fail("Postcondition failed: incorrect output behavior".into()));
  }

  return HarnessResult::Passed
}

/** Contract-based test harness for the compute entry point
  */
pub fn testComputeCB_container(container: PreStateContainer) -> HarnessResult
{
  return testComputeCB(container.api_analysis_report_in, container.api_analysis_request)
}

#[macro_export]
macro_rules!
testComputeCB_macro {
  (
    $test_name: ident,
    config: $config:expr,
    api_analysis_report_in: $api_analysis_report_in_strat:expr,
    api_analysis_request: $api_analysis_request_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (api_analysis_report_in, api_analysis_request)
            in ($api_analysis_report_in_strat, $api_analysis_request_strat)
      ) {
        match$crate::test::util::cb_apis::testComputeCB(api_analysis_report_in, api_analysis_request) {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            return Err(proptest::test_runner::TestCaseError::reject(
              "Precondition failed: invalid input combination",
            ))
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param In_counter pre-state state variable
  * @param In_is_invalid2 pre-state state variable
  * @param In_is_valid1 pre-state state variable
  * @param In_since_result pre-state state variable
  * @param api_analysis_report_in incoming event data port
  * @param api_analysis_request incoming event data port
  */
pub fn testComputeCBwGSV(
  In_counter: u32,
  In_is_invalid2: bool,
  In_is_valid1: bool,
  In_since_result: bool,
  api_analysis_report_in: Option<Common::AnalysisReport_Impl>,
  api_analysis_request: Option<Common::AnalysisRequest_Impl>) -> HarnessResult
{
  // Initialize the app
  crate::cpuSw_reportMonitor_reportMonitor_initialize();

  // [PutInPorts]: Set values on the input ports
  put_analysis_report_in(api_analysis_report_in);
  put_analysis_request(api_analysis_request);

  // [SetInStateVars]: set the pre-state values of state variables
  put_counter(In_counter);
  put_is_invalid2(In_is_invalid2);
  put_is_valid1(In_is_valid1);
  put_since_result(In_since_result);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::cpuSw_reportMonitor_reportMonitor_timeTriggered();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let counter = get_counter();
  let is_invalid2 = get_is_invalid2();
  let is_valid1 = get_is_valid1();
  let since_result = get_since_result();
  let api_alert = get_alert();
  let api_analysis_report_out = get_analysis_report_out();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::compute_CEP_Post(In_counter, In_is_invalid2, In_is_valid1, In_since_result, counter, is_invalid2, is_valid1, since_result, api_analysis_report_in, api_analysis_request, api_alert, api_analysis_report_out) {
    return HarnessResult::FailedPostcondition(TestCaseError::Fail("Postcondition failed: incorrect output behavior".into()));
  }

  return HarnessResult::Passed
}

/** Contract-based test harness for the compute entry point
  */
pub fn testComputeCBwGSV_container(container: PreStateContainer_wGSV) -> HarnessResult
{
  return testComputeCBwGSV(container.In_counter, container.In_is_invalid2, container.In_is_valid1, container.In_since_result, container.api_analysis_report_in, container.api_analysis_request)
}

#[macro_export]
macro_rules!
testComputeCBwGSV_macro {
  (
    $test_name: ident,
    config: $config:expr,
    In_counter: $In_counter_strat:expr,
    In_is_invalid2: $In_is_invalid2_strat:expr,
    In_is_valid1: $In_is_valid1_strat:expr,
    In_since_result: $In_since_result_strat:expr,
    api_analysis_report_in: $api_analysis_report_in_strat:expr,
    api_analysis_request: $api_analysis_request_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (In_counter, In_is_invalid2, In_is_valid1, In_since_result, api_analysis_report_in, api_analysis_request)
            in ($In_counter_strat, $In_is_invalid2_strat, $In_is_valid1_strat, $In_since_result_strat, $api_analysis_report_in_strat, $api_analysis_request_strat)
      ) {
        match $crate::test::util::cb_apis::testComputeCBwGSV(In_counter, In_is_invalid2, In_is_valid1, In_since_result, api_analysis_report_in, api_analysis_request) {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            return Err(proptest::test_runner::TestCaseError::reject(
              "Precondition failed: invalid input combination",
            ))
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}
