// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {
  pub const Common_encryptedPayload_Impl_BYTE_SIZE: usize = 1024;
  pub const Common_encryptedPayload_Impl_DIM_0: usize = 1024;

  pub type encryptedPayload_Impl = [u8; Common_encryptedPayload_Impl_DIM_0];
}