// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait cpuSw_dataManager_dataManager_dataManager_Api {}

  pub trait cpuSw_dataManager_dataManager_dataManager_Put_Api: cpuSw_dataManager_dataManager_dataManager_Api {
    #[verifier::external_body]
    fn unverified_put_encrypted_log(
      &mut self,
      value: Common::StoredLogFile_Impl)
    {
      extern_api::unsafe_put_encrypted_log(&value);
    }

    #[verifier::external_body]
    fn unverified_put_storage_request(
      &mut self,
      value: Common::AnalysisRequest_Impl)
    {
      extern_api::unsafe_put_storage_request(&value);
    }

    #[verifier::external_body]
    fn unverified_put_response_log(
      &mut self,
      value: Common::AnalysisResponse_Impl)
    {
      extern_api::unsafe_put_response_log(&value);
    }
  }

  pub trait cpuSw_dataManager_dataManager_dataManager_Get_Api: cpuSw_dataManager_dataManager_dataManager_Api {
    #[verifier::external_body]
    fn unverified_get_HMD_log(
      &mut self,
      value: &Ghost<Option<Common::Log_Impl>>) -> (res : Option<Common::Log_Impl>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_HMD_log();
    }

    #[verifier::external_body]
    fn unverified_get_request_log(
      &mut self,
      value: &Ghost<Option<Common::AnalysisRequest_Impl>>) -> (res : Option<Common::AnalysisRequest_Impl>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_request_log();
    }

    #[verifier::external_body]
    fn unverified_get_encrypted_response(
      &mut self,
      value: &Ghost<Option<Common::EncryptedAnalysisResponse_Impl>>) -> (res : Option<Common::EncryptedAnalysisResponse_Impl>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_encrypted_response();
    }

    #[verifier::external_body]
    fn unverified_get_zeroize(
      &mut self,
      value: &Ghost<Option<u8>>) -> (res : bool)
      ensures
        res == value@.is_some(),
    {
      return extern_api::unsafe_get_zeroize();
    }
  }

  pub trait cpuSw_dataManager_dataManager_dataManager_Full_Api: cpuSw_dataManager_dataManager_dataManager_Put_Api + cpuSw_dataManager_dataManager_dataManager_Get_Api {}

  pub struct cpuSw_dataManager_dataManager_dataManager_Application_Api<API: cpuSw_dataManager_dataManager_dataManager_Api> {
    pub api: API,

    pub ghost HMD_log: Option<Common::Log_Impl>,
    pub ghost request_log: Option<Common::AnalysisRequest_Impl>,
    pub ghost encrypted_response: Option<Common::EncryptedAnalysisResponse_Impl>,
    pub ghost zeroize: Option<u8>,
    pub ghost encrypted_log: Option<Common::StoredLogFile_Impl>,
    pub ghost storage_request: Option<Common::AnalysisRequest_Impl>,
    pub ghost response_log: Option<Common::AnalysisResponse_Impl>,
  }

  impl<API: cpuSw_dataManager_dataManager_dataManager_Put_Api> cpuSw_dataManager_dataManager_dataManager_Application_Api<API> {
    pub fn put_encrypted_log(
      &mut self,
      value: Common::StoredLogFile_Impl)
      ensures
        old(self).HMD_log == final(self).HMD_log,
        final(self).encrypted_log == Some(value),
        old(self).request_log == final(self).request_log,
        old(self).storage_request == final(self).storage_request,
        old(self).encrypted_response == final(self).encrypted_response,
        old(self).response_log == final(self).response_log,
        old(self).zeroize == final(self).zeroize,
    {
      self.api.unverified_put_encrypted_log(value);
      proof { self.encrypted_log = Some(value); }
    }
    pub fn put_storage_request(
      &mut self,
      value: Common::AnalysisRequest_Impl)
      ensures
        old(self).HMD_log == final(self).HMD_log,
        old(self).encrypted_log == final(self).encrypted_log,
        old(self).request_log == final(self).request_log,
        final(self).storage_request == Some(value),
        old(self).encrypted_response == final(self).encrypted_response,
        old(self).response_log == final(self).response_log,
        old(self).zeroize == final(self).zeroize,
    {
      self.api.unverified_put_storage_request(value);
      proof { self.storage_request = Some(value); }
    }
    pub fn put_response_log(
      &mut self,
      value: Common::AnalysisResponse_Impl)
      ensures
        old(self).HMD_log == final(self).HMD_log,
        old(self).encrypted_log == final(self).encrypted_log,
        old(self).request_log == final(self).request_log,
        old(self).storage_request == final(self).storage_request,
        old(self).encrypted_response == final(self).encrypted_response,
        final(self).response_log == Some(value),
        old(self).zeroize == final(self).zeroize,
    {
      self.api.unverified_put_response_log(value);
      proof { self.response_log = Some(value); }
    }
  }

  impl<API: cpuSw_dataManager_dataManager_dataManager_Get_Api> cpuSw_dataManager_dataManager_dataManager_Application_Api<API> {
    pub fn get_HMD_log(&mut self) -> (res : Option<Common::Log_Impl>)
      ensures
        old(self).HMD_log == final(self).HMD_log,
        res == final(self).HMD_log,
        old(self).encrypted_log == final(self).encrypted_log,
        old(self).request_log == final(self).request_log,
        old(self).storage_request == final(self).storage_request,
        old(self).encrypted_response == final(self).encrypted_response,
        old(self).response_log == final(self).response_log,
        old(self).zeroize == final(self).zeroize,
    {
      self.api.unverified_get_HMD_log(&Ghost(self.HMD_log))
    }
    pub fn get_request_log(&mut self) -> (res : Option<Common::AnalysisRequest_Impl>)
      ensures
        old(self).HMD_log == final(self).HMD_log,
        old(self).encrypted_log == final(self).encrypted_log,
        old(self).request_log == final(self).request_log,
        res == final(self).request_log,
        old(self).storage_request == final(self).storage_request,
        old(self).encrypted_response == final(self).encrypted_response,
        old(self).response_log == final(self).response_log,
        old(self).zeroize == final(self).zeroize,
    {
      self.api.unverified_get_request_log(&Ghost(self.request_log))
    }
    pub fn get_encrypted_response(&mut self) -> (res : Option<Common::EncryptedAnalysisResponse_Impl>)
      ensures
        old(self).HMD_log == final(self).HMD_log,
        old(self).encrypted_log == final(self).encrypted_log,
        old(self).request_log == final(self).request_log,
        old(self).storage_request == final(self).storage_request,
        old(self).encrypted_response == final(self).encrypted_response,
        res == final(self).encrypted_response,
        old(self).response_log == final(self).response_log,
        old(self).zeroize == final(self).zeroize,
    {
      self.api.unverified_get_encrypted_response(&Ghost(self.encrypted_response))
    }
    pub fn get_zeroize(&mut self) -> (res : bool)
      ensures
        old(self).HMD_log == final(self).HMD_log,
        old(self).encrypted_log == final(self).encrypted_log,
        old(self).request_log == final(self).request_log,
        old(self).storage_request == final(self).storage_request,
        old(self).encrypted_response == final(self).encrypted_response,
        old(self).response_log == final(self).response_log,
        old(self).zeroize == final(self).zeroize,
        res == final(self).zeroize.is_some(),
    {
      self.api.unverified_get_zeroize(&Ghost(self.zeroize))
    }
  }

  pub struct cpuSw_dataManager_dataManager_dataManager_Initialization_Api;
  impl cpuSw_dataManager_dataManager_dataManager_Api for cpuSw_dataManager_dataManager_dataManager_Initialization_Api {}
  impl cpuSw_dataManager_dataManager_dataManager_Put_Api for cpuSw_dataManager_dataManager_dataManager_Initialization_Api {}

  pub const fn init_api() -> cpuSw_dataManager_dataManager_dataManager_Application_Api<cpuSw_dataManager_dataManager_dataManager_Initialization_Api> {
    return cpuSw_dataManager_dataManager_dataManager_Application_Api {
      api: cpuSw_dataManager_dataManager_dataManager_Initialization_Api {},

      HMD_log: None,
      request_log: None,
      encrypted_response: None,
      zeroize: None,
      encrypted_log: None,
      storage_request: None,
      response_log: None
    }
  }

  pub struct cpuSw_dataManager_dataManager_dataManager_Compute_Api;
  impl cpuSw_dataManager_dataManager_dataManager_Api for cpuSw_dataManager_dataManager_dataManager_Compute_Api {}
  impl cpuSw_dataManager_dataManager_dataManager_Put_Api for cpuSw_dataManager_dataManager_dataManager_Compute_Api {}
  impl cpuSw_dataManager_dataManager_dataManager_Get_Api for cpuSw_dataManager_dataManager_dataManager_Compute_Api {}
  impl cpuSw_dataManager_dataManager_dataManager_Full_Api for cpuSw_dataManager_dataManager_dataManager_Compute_Api {}

  pub const fn compute_api() -> cpuSw_dataManager_dataManager_dataManager_Application_Api<cpuSw_dataManager_dataManager_dataManager_Compute_Api> {
    return cpuSw_dataManager_dataManager_dataManager_Application_Api {
      api: cpuSw_dataManager_dataManager_dataManager_Compute_Api {},

      HMD_log: None,
      request_log: None,
      encrypted_response: None,
      zeroize: None,
      encrypted_log: None,
      storage_request: None,
      response_log: None
    }
  }

}