// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

pub fn IS_ZEROIZED(response: Common::Response_Impl) -> bool
{
  MATRICS_Model_Transformations::IS_NULL_REQUEST(response.request) &
    (response.validLogCount == 0u32) &
    (response.moreAvailable == false) &
    (response.nextStartTime == 0u64) &
    (0..=response.logs.len() - 1).all(|response_log_index| MATRICS_Model_Transformations::IS_NULL_LOG(response.logs[response_log_index]))
}

/** Initialize EntryPointContract
  *
  * guarantee defaultZeroize
  * @param zeroize_cmd post-state state variable
  */
pub fn initialize_defaultZeroize(zeroize_cmd: bool) -> bool
{
  zeroize_cmd == false
}

/** IEP-Guar: Initialize Entrypoint for dataManager
  *
  * @param zeroize_cmd post-state state variable
  * @param api_encrypted_log outgoing event data port
  * @param api_response_log outgoing event data port
  * @param api_storage_request outgoing event data port
  */
pub fn initialize_IEP_Guar(
  zeroize_cmd: bool,
  api_encrypted_log: Option<Common::StoredLogFile_Impl>,
  api_response_log: Option<Common::AnalysisResponse_Impl>,
  api_storage_request: Option<Common::AnalysisRequest_Impl>) -> bool
{
  initialize_defaultZeroize(zeroize_cmd)
}

/** IEP-Post: Initialize Entrypoint Post-Condition
  *
  * @param zeroize_cmd post-state state variable
  * @param api_encrypted_log outgoing event data port
  * @param api_response_log outgoing event data port
  * @param api_storage_request outgoing event data port
  */
pub fn initialize_IEP_Post(
  zeroize_cmd: bool,
  api_encrypted_log: Option<Common::StoredLogFile_Impl>,
  api_response_log: Option<Common::AnalysisResponse_Impl>,
  api_storage_request: Option<Common::AnalysisRequest_Impl>) -> bool
{
  initialize_IEP_Guar(zeroize_cmd, api_encrypted_log, api_response_log, api_storage_request)
}

/** Compute Entrypoint Contract
  *
  * guarantee zeroize_cmd_variable
  *   G: Once a zeroize command is seen, always zeroize.
  * @param In_zeroize_cmd pre-state state variable
  * @param zeroize_cmd post-state state variable
  * @param api_zeroize incoming event port
  */
pub fn compute_spec_zeroize_cmd_variable_guarantee(
  In_zeroize_cmd: bool,
  zeroize_cmd: bool,
  api_zeroize: Option<u8>) -> bool
{
  zeroize_cmd == (api_zeroize.is_some() || In_zeroize_cmd)
}

/** Compute Entrypoint Contract
  *
  * guarantee Zeroize_Payload
  *   G: Zeroize outgoing responses once an alert is received and when a request has been made.
  * @param zeroize_cmd post-state state variable
  * @param api_request_log incoming event data port
  * @param api_response_log outgoing event data port
  */
pub fn compute_spec_Zeroize_Payload_guarantee(
  zeroize_cmd: bool,
  api_request_log: Option<Common::AnalysisRequest_Impl>,
  api_response_log: Option<Common::AnalysisResponse_Impl>) -> bool
{
  implies!(
    zeroize_cmd & api_request_log.is_some(),
    IS_ZEROIZED(api_response_log.unwrap().payload))
}

/** CEP-T-Guar: Top-level guarantee contracts for dataManager's compute entrypoint
  *
  * @param In_zeroize_cmd pre-state state variable
  * @param zeroize_cmd post-state state variable
  * @param api_zeroize incoming event port
  * @param api_request_log incoming event data port
  * @param api_response_log outgoing event data port
  */
pub fn compute_CEP_T_Guar(
  In_zeroize_cmd: bool,
  zeroize_cmd: bool,
  api_zeroize: Option<u8>,
  api_request_log: Option<Common::AnalysisRequest_Impl>,
  api_response_log: Option<Common::AnalysisResponse_Impl>) -> bool
{
  let r0: bool = compute_spec_zeroize_cmd_variable_guarantee(In_zeroize_cmd, zeroize_cmd, api_zeroize);
  let r1: bool = compute_spec_Zeroize_Payload_guarantee(zeroize_cmd, api_request_log, api_response_log);

  return r0 && r1;
}

/** CEP-Post: Compute Entrypoint Post-Condition for dataManager
  *
  * @param In_zeroize_cmd pre-state state variable
  * @param zeroize_cmd post-state state variable
  * @param api_zeroize incoming event port
  * @param api_HMD_log incoming event data port
  * @param api_encrypted_response incoming event data port
  * @param api_request_log incoming event data port
  * @param api_encrypted_log outgoing event data port
  * @param api_response_log outgoing event data port
  * @param api_storage_request outgoing event data port
  */
pub fn compute_CEP_Post(
  In_zeroize_cmd: bool,
  zeroize_cmd: bool,
  api_zeroize: Option<u8>,
  api_HMD_log: Option<Common::Log_Impl>,
  api_encrypted_response: Option<Common::EncryptedAnalysisResponse_Impl>,
  api_request_log: Option<Common::AnalysisRequest_Impl>,
  api_encrypted_log: Option<Common::StoredLogFile_Impl>,
  api_response_log: Option<Common::AnalysisResponse_Impl>,
  api_storage_request: Option<Common::AnalysisRequest_Impl>) -> bool
{
  // CEP-Guar: guarantee clauses of dataManager's compute entrypoint
  let r0: bool = compute_CEP_T_Guar(In_zeroize_cmd, zeroize_cmd, api_zeroize, api_request_log, api_response_log);

  return r0;
}
