// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! C-interface for the component.
//! This code must be unsafe.
//! Assumptions about correctness are introduced and need to be verified by other means.

use data::*;

#[cfg(test)]
use std::sync::Mutex;

#[cfg(not(test))]
extern "C" {
  fn get_HMD_log(value: *mut Common::Log_Impl) -> bool;
  fn get_request_log(value: *mut Common::AnalysisRequest_Impl) -> bool;
  fn get_encrypted_response(value: *mut Common::EncryptedAnalysisResponse_Impl) -> bool;
  fn get_zeroize() -> bool;
  fn put_encrypted_log(value: *mut Common::StoredLogFile_Impl) -> bool;
  fn put_storage_request(value: *mut Common::AnalysisRequest_Impl) -> bool;
  fn put_response_log(value: *mut Common::AnalysisResponse_Impl) -> bool;
}

pub fn unsafe_get_HMD_log() -> Option<Common::Log_Impl>
{
  unsafe {
    let value: *mut Common::Log_Impl = &mut Common::Log_Impl::default();
    if (get_HMD_log(value)) {
      return Some(*value);
    } else {
      return None;
    }
  }
}

pub fn unsafe_get_request_log() -> Option<Common::AnalysisRequest_Impl>
{
  unsafe {
    let value: *mut Common::AnalysisRequest_Impl = &mut Common::AnalysisRequest_Impl::default();
    if (get_request_log(value)) {
      return Some(*value);
    } else {
      return None;
    }
  }
}

pub fn unsafe_get_encrypted_response() -> Option<Common::EncryptedAnalysisResponse_Impl>
{
  unsafe {
    let value: *mut Common::EncryptedAnalysisResponse_Impl = &mut Common::EncryptedAnalysisResponse_Impl::default();
    if (get_encrypted_response(value)) {
      return Some(*value);
    } else {
      return None;
    }
  }
}

pub fn unsafe_get_zeroize() -> bool
{
  unsafe {
    return get_zeroize();
  }
}

pub fn unsafe_put_encrypted_log(value: &Common::StoredLogFile_Impl) -> bool
{
  unsafe {
    return put_encrypted_log(value as *const Common::StoredLogFile_Impl as *mut Common::StoredLogFile_Impl);
  }
}

pub fn unsafe_put_storage_request(value: &Common::AnalysisRequest_Impl) -> bool
{
  unsafe {
    return put_storage_request(value as *const Common::AnalysisRequest_Impl as *mut Common::AnalysisRequest_Impl);
  }
}

pub fn unsafe_put_response_log(value: &Common::AnalysisResponse_Impl) -> bool
{
  unsafe {
    return put_response_log(value as *const Common::AnalysisResponse_Impl as *mut Common::AnalysisResponse_Impl);
  }
}

//////////////////////////////////////////////////////////////////////////////////
// Testing Versions
//////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
lazy_static::lazy_static! {
  // simulate the global C variables that point to the microkit shared memory regions.  In a full
  // microkit system we would be able to mutate the shared memory for out ports since they're r/w,
  // but we couldn't do that for in ports since they are read-only
  pub static ref IN_HMD_log: Mutex<Option<Common::Log_Impl>> = Mutex::new(None);
  pub static ref IN_request_log: Mutex<Option<Common::AnalysisRequest_Impl>> = Mutex::new(None);
  pub static ref IN_encrypted_response: Mutex<Option<Common::EncryptedAnalysisResponse_Impl>> = Mutex::new(None);
  pub static ref IN_zeroize: Mutex<Option<u8>> = Mutex::new(None);
  pub static ref OUT_encrypted_log: Mutex<Option<Common::StoredLogFile_Impl>> = Mutex::new(None);
  pub static ref OUT_storage_request: Mutex<Option<Common::AnalysisRequest_Impl>> = Mutex::new(None);
  pub static ref OUT_response_log: Mutex<Option<Common::AnalysisResponse_Impl>> = Mutex::new(None);
}

#[cfg(test)]
pub fn initialize_test_globals() {
  unsafe {
    *IN_HMD_log.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_request_log.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_encrypted_response.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_zeroize.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_encrypted_log.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_storage_request.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_response_log.lock().unwrap_or_else(|e| e.into_inner()) = None;
  }
}

#[cfg(test)]
pub fn get_HMD_log(value: *mut Common::Log_Impl) -> bool
{
  unsafe {
    match *IN_HMD_log.lock().unwrap_or_else(|e| e.into_inner()) {
      Some(v) => {
        *value = v;
        return true;
      },
      None => return false,
    }
  }
}

#[cfg(test)]
pub fn get_request_log(value: *mut Common::AnalysisRequest_Impl) -> bool
{
  unsafe {
    match *IN_request_log.lock().unwrap_or_else(|e| e.into_inner()) {
      Some(v) => {
        *value = v;
        return true;
      },
      None => return false,
    }
  }
}

#[cfg(test)]
pub fn get_encrypted_response(value: *mut Common::EncryptedAnalysisResponse_Impl) -> bool
{
  unsafe {
    match *IN_encrypted_response.lock().unwrap_or_else(|e| e.into_inner()) {
      Some(v) => {
        *value = v;
        return true;
      },
      None => return false,
    }
  }
}

#[cfg(test)]
pub fn get_zeroize() -> bool
{
  unsafe {
    match *IN_zeroize.lock().unwrap_or_else(|e| e.into_inner()) {
      Some(v) => {
        return true;
      },
      None => return false,
    }
  }
}

#[cfg(test)]
pub fn put_encrypted_log(value: *mut Common::StoredLogFile_Impl) -> bool
{
  unsafe {
    *OUT_encrypted_log.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_storage_request(value: *mut Common::AnalysisRequest_Impl) -> bool
{
  unsafe {
    *OUT_storage_request.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_response_log(value: *mut Common::AnalysisResponse_Impl) -> bool
{
  unsafe {
    *OUT_response_log.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}
