// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Flat system state for the system-level verification conditions.
//! One field per AADL connection channel (owned by its source out port),
//! unconnected port, and GUMBO state variable across all components.

use data::*;
use vstd::prelude::*;

verus! {

pub struct SystemState {
  // -- GroundStation_Impl_Instance.cpuSw_wifiDriver_wifiDriver.wifiDriver --
  pub wifiSend: Option<Common::OutgoingWifiMessage_Impl>, // channel
  pub HMD_log: Option<Common::EncryptedMessage_Impl>, // channel
  pub analysis_request: Option<Common::AnalysisRequest_Impl>, // channel
  pub alert_cmd: bool, // state variable

  // -- GroundStation_Impl_Instance.cpuSw_wifiDriver_wifiDriverVM.wifiDriver --
  pub wifiRecvIn: Option<Common::IncomingWifiMessage_Impl>, // channel
  pub wifiRecvOut: Option<Common::IncomingWifiMessage_Impl>, // channel
  pub wifiSendOut: Option<Common::OutgoingWifiMessage_Impl>, // channel

  // -- GroundStation_Impl_Instance.cpuSw_btDriver.btDriver --
  pub btRecv: Option<Common::DummyMessage_Impl>, // channel
  pub btSend: Option<Common::DummyMessage_Impl>, // channel

  // -- GroundStation_Impl_Instance.cpuSw_usbDriver.usbDriver --
  pub usbRecv: Option<Common::DummyMessage_Impl>, // channel
  pub usbSend: Option<Common::DummyMessage_Impl>, // channel

  // -- GroundStation_Impl_Instance.cpuSw_dataManager_dataManager.dataManager --
  pub encrypted_log: Option<Common::StoredLogFile_Impl>, // channel
  pub storage_request: Option<Common::AnalysisRequest_Impl>, // channel
  pub data_manager_response: Option<Common::AnalysisResponse_Impl>, // channel
  pub data_manager_zeroize_cmd: bool, // state variable

  // -- GroundStation_Impl_Instance.cpuSw_dataManager_dataStorage.dataStorage --
  pub encrypted_response: Option<Common::EncryptedAnalysisResponse_Impl>, // channel
  pub data_storage_cache: Common::EncryptedLogArray_Impl, // state variable
  pub data_storage_zeroize_cmd: bool, // state variable

  // -- GroundStation_Impl_Instance.cpuSw_dataAnalysis.dataAnalysis --
  pub data_manager_request: Option<Common::AnalysisRequest_Impl>, // channel
  pub analysis_report: Option<Common::AnalysisResponse_Impl>, // channel

  // -- GroundStation_Impl_Instance.cpuSw_decryptor.decryptor --
  pub HMD_log_out: Option<Common::Log_Impl>, // channel

  // -- GroundStation_Impl_Instance.cpuSw_encryptor.encryptor --
  pub analysis_report_out: Option<Common::OutgoingWifiMessage_Impl>, // channel

  // -- GroundStation_Impl_Instance.cpuSw_logMonitor.logMonitor --
  pub log_response_out: Option<Common::AnalysisResponse_Impl>, // channel
  pub log_alert: Option<u8>, // channel
  pub storage_alert: Option<u8>, // channel
  pub log_monitor_since_result: bool, // state variable
  pub log_is_valid: bool, // state variable
  pub log_historically_no_alert: bool, // state variable

  // -- GroundStation_Impl_Instance.cpuSw_reportMonitor.reportMonitor --
  pub report_out: Option<Common::OutgoingWifiMessage_Impl>, // channel
  pub report_alert: Option<u8>, // channel
  pub counter: u32, // state variable
  pub report_monitor_since_result: bool, // state variable
  pub is_valid1: bool, // state variable
  pub is_invalid2: bool, // state variable

  // -- GroundStation_Impl_Instance.cpuSw_firewall.firewall --
  pub firewall_request_out: Option<Common::AnalysisRequest_Impl>, // channel
}

} // verus!
