// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Place-assertion spec functions of property `zeroize_storage_before_next_datamanager` -- one per
//! point its decoration binds (unbound points carry `true`, design D5).

#![allow(non_snake_case)]
#![allow(unused_imports)]

use data::*;
use vstd::prelude::*;

use crate::assertions::*;
use crate::system_state::SystemState;

verus! {

/** property zeroize_storage_before_next_datamanager, bound 'after log_monitor' (place after_log_monitor)
  *   logMonitor sends the storage-zeroize event
  */
pub open spec fn sys_assert_zeroize_storage_before_next_datamanager_after_log_monitor(st: SystemState) -> bool
{
  (st.log_response_in.is_some() && !st.log_is_valid) ==>
    st.storage_alert.is_some()
}

/** property zeroize_storage_before_next_datamanager, bound 'after data_storage_3' (place after_data_storage_3)
  *   This is also the place immediately before
  *   data_manager_3; storage's zeroize latch is active and its
  *   encrypted-log cache has been zeroized
  */
pub open spec fn sys_assert_zeroize_storage_before_next_datamanager_after_data_storage_3(st: SystemState) -> bool
{
  (st.log_response_in.is_some() && !st.log_is_valid) ==>
    (st.data_storage_zeroize_cmd && MATRICS_Model_Transformations::IS_ZEROIZED_ENCRYPTED_LOG_ARRAY_spec(st.data_storage_cache))
}

} // verus!
