// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {

  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct MsgHeader_Impl {
    pub client: u32
  }

  impl Default for MsgHeader_Impl {
    fn default() -> Self
    {
      Self { client: 0 }
    }
  }

}