#include <stdint.h>
#include <microkit.h>

#define PORT_TO_CPUSW_BTDRIVER_BTDRIVER_MON 61
#define PORT_TO_CPUSW_USBDRIVER_USBDRIVER_MON 59
#define PORT_TO_CPUSW_DATAMANAGER_DATAMANAGER_MON 57
#define PORT_TO_CPUSW_DATAANALYSIS_DATAANALYSIS_MON 55
#define PORT_TO_CPUSW_DECRYPTOR_DECRYPTOR_MON 53
#define PORT_TO_CPUSW_ENCRYPTOR_ENCRYPTOR_MON 51
#define PORT_TO_CPUSW_LOGMONITOR_LOGMONITOR_MON 49
#define PORT_TO_CPUSW_REPORTMONITOR_REPORTMONITOR_MON 47
#define PORT_TO_CPUSW_FIREWALL_FIREWALL_MON 45
#define PORT_TO_CPUSW_WIFIDRIVER_WIFIDRIVER_WIFIDRIVER_MON 43
#define PORT_TO_CPUSW_WIFIDRIVER_WIFIDRIVERVM_WIFIDRIVER_MON 41

void init(void) {}

void notified(microkit_channel channel) {
  switch(channel) {
    case PORT_TO_CPUSW_BTDRIVER_BTDRIVER_MON:
      microkit_notify(PORT_TO_CPUSW_BTDRIVER_BTDRIVER_MON);
      break;
    case PORT_TO_CPUSW_USBDRIVER_USBDRIVER_MON:
      microkit_notify(PORT_TO_CPUSW_USBDRIVER_USBDRIVER_MON);
      break;
    case PORT_TO_CPUSW_DATAMANAGER_DATAMANAGER_MON:
      microkit_notify(PORT_TO_CPUSW_DATAMANAGER_DATAMANAGER_MON);
      break;
    case PORT_TO_CPUSW_DATAANALYSIS_DATAANALYSIS_MON:
      microkit_notify(PORT_TO_CPUSW_DATAANALYSIS_DATAANALYSIS_MON);
      break;
    case PORT_TO_CPUSW_DECRYPTOR_DECRYPTOR_MON:
      microkit_notify(PORT_TO_CPUSW_DECRYPTOR_DECRYPTOR_MON);
      break;
    case PORT_TO_CPUSW_ENCRYPTOR_ENCRYPTOR_MON:
      microkit_notify(PORT_TO_CPUSW_ENCRYPTOR_ENCRYPTOR_MON);
      break;
    case PORT_TO_CPUSW_LOGMONITOR_LOGMONITOR_MON:
      microkit_notify(PORT_TO_CPUSW_LOGMONITOR_LOGMONITOR_MON);
      break;
    case PORT_TO_CPUSW_REPORTMONITOR_REPORTMONITOR_MON:
      microkit_notify(PORT_TO_CPUSW_REPORTMONITOR_REPORTMONITOR_MON);
      break;
    case PORT_TO_CPUSW_FIREWALL_FIREWALL_MON:
      microkit_notify(PORT_TO_CPUSW_FIREWALL_FIREWALL_MON);
      break;
    case PORT_TO_CPUSW_WIFIDRIVER_WIFIDRIVER_WIFIDRIVER_MON:
      microkit_notify(PORT_TO_CPUSW_WIFIDRIVER_WIFIDRIVER_WIFIDRIVER_MON);
      break;
    case PORT_TO_CPUSW_WIFIDRIVER_WIFIDRIVERVM_WIFIDRIVER_MON:
      microkit_notify(PORT_TO_CPUSW_WIFIDRIVER_WIFIDRIVERVM_WIFIDRIVER_MON);
      break;
  }
}
