// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait cpuSw_reportMonitor_reportMonitor_Api {}

  pub trait cpuSw_reportMonitor_reportMonitor_Put_Api: cpuSw_reportMonitor_reportMonitor_Api {
    #[verifier::external_body]
    fn unverified_put_analysis_report_out(
      &mut self,
      value: Common::OutgoingWifiMessage_Impl)
    {
      extern_api::unsafe_put_analysis_report_out(&value);
    }

    #[verifier::external_body]
    fn unverified_put_alert_out(&mut self)
    {
      extern_api::unsafe_put_alert_out();
    }
  }

  pub trait cpuSw_reportMonitor_reportMonitor_Get_Api: cpuSw_reportMonitor_reportMonitor_Api {
    #[verifier::external_body]
    fn unverified_get_analysis_request(
      &mut self,
      value: &Ghost<Option<Common::AnalysisRequest_Impl>>) -> (res : Option<Common::AnalysisRequest_Impl>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_analysis_request();
    }

    #[verifier::external_body]
    fn unverified_get_analysis_report_in(
      &mut self,
      value: &Ghost<Option<Common::OutgoingWifiMessage_Impl>>) -> (res : Option<Common::OutgoingWifiMessage_Impl>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_analysis_report_in();
    }
  }

  pub trait cpuSw_reportMonitor_reportMonitor_Full_Api: cpuSw_reportMonitor_reportMonitor_Put_Api + cpuSw_reportMonitor_reportMonitor_Get_Api {}

  pub struct cpuSw_reportMonitor_reportMonitor_Application_Api<API: cpuSw_reportMonitor_reportMonitor_Api> {
    pub api: API,

    pub ghost analysis_request: Option<Common::AnalysisRequest_Impl>,
    pub ghost analysis_report_in: Option<Common::OutgoingWifiMessage_Impl>,
    pub ghost analysis_report_out: Option<Common::OutgoingWifiMessage_Impl>,
    pub ghost alert_out: Option<u8>,
  }

  impl<API: cpuSw_reportMonitor_reportMonitor_Put_Api> cpuSw_reportMonitor_reportMonitor_Application_Api<API> {
    pub fn put_analysis_report_out(
      &mut self,
      value: Common::OutgoingWifiMessage_Impl)
      ensures
        old(self).analysis_request == final(self).analysis_request,
        old(self).analysis_report_in == final(self).analysis_report_in,
        final(self).analysis_report_out == Some(value),
        old(self).alert_out == final(self).alert_out,
    {
      self.api.unverified_put_analysis_report_out(value);
      proof { self.analysis_report_out = Some(value); }
    }
    pub fn put_alert_out(&mut self)
      ensures
        old(self).analysis_request == final(self).analysis_request,
        old(self).analysis_report_in == final(self).analysis_report_in,
        old(self).analysis_report_out == final(self).analysis_report_out,
        final(self).alert_out == Some(0u8),
    {
      self.api.unverified_put_alert_out();
      proof { self.alert_out = Some(0u8); }
    }
  }

  impl<API: cpuSw_reportMonitor_reportMonitor_Get_Api> cpuSw_reportMonitor_reportMonitor_Application_Api<API> {
    pub fn get_analysis_request(&mut self) -> (res : Option<Common::AnalysisRequest_Impl>)
      ensures
        old(self).analysis_request == final(self).analysis_request,
        res == final(self).analysis_request,
        old(self).analysis_report_in == final(self).analysis_report_in,
        old(self).analysis_report_out == final(self).analysis_report_out,
        old(self).alert_out == final(self).alert_out,
    {
      self.api.unverified_get_analysis_request(&Ghost(self.analysis_request))
    }
    pub fn get_analysis_report_in(&mut self) -> (res : Option<Common::OutgoingWifiMessage_Impl>)
      ensures
        old(self).analysis_request == final(self).analysis_request,
        old(self).analysis_report_in == final(self).analysis_report_in,
        res == final(self).analysis_report_in,
        old(self).analysis_report_out == final(self).analysis_report_out,
        old(self).alert_out == final(self).alert_out,
    {
      self.api.unverified_get_analysis_report_in(&Ghost(self.analysis_report_in))
    }
  }

  pub struct cpuSw_reportMonitor_reportMonitor_Initialization_Api;
  impl cpuSw_reportMonitor_reportMonitor_Api for cpuSw_reportMonitor_reportMonitor_Initialization_Api {}
  impl cpuSw_reportMonitor_reportMonitor_Put_Api for cpuSw_reportMonitor_reportMonitor_Initialization_Api {}

  pub const fn init_api() -> cpuSw_reportMonitor_reportMonitor_Application_Api<cpuSw_reportMonitor_reportMonitor_Initialization_Api> {
    return cpuSw_reportMonitor_reportMonitor_Application_Api {
      api: cpuSw_reportMonitor_reportMonitor_Initialization_Api {},

      analysis_request: None,
      analysis_report_in: None,
      analysis_report_out: None,
      alert_out: None
    }
  }

  pub struct cpuSw_reportMonitor_reportMonitor_Compute_Api;
  impl cpuSw_reportMonitor_reportMonitor_Api for cpuSw_reportMonitor_reportMonitor_Compute_Api {}
  impl cpuSw_reportMonitor_reportMonitor_Put_Api for cpuSw_reportMonitor_reportMonitor_Compute_Api {}
  impl cpuSw_reportMonitor_reportMonitor_Get_Api for cpuSw_reportMonitor_reportMonitor_Compute_Api {}
  impl cpuSw_reportMonitor_reportMonitor_Full_Api for cpuSw_reportMonitor_reportMonitor_Compute_Api {}

  pub const fn compute_api() -> cpuSw_reportMonitor_reportMonitor_Application_Api<cpuSw_reportMonitor_reportMonitor_Compute_Api> {
    return cpuSw_reportMonitor_reportMonitor_Application_Api {
      api: cpuSw_reportMonitor_reportMonitor_Compute_Api {},

      analysis_request: None,
      analysis_report_in: None,
      analysis_report_out: None,
      alert_out: None
    }
  }

}