// Do not edit this file as it will be overwritten if codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** Compute Entrypoint Contract
  *
  * guarantee Payload_Decrypted
  *   G: Outgoing payload is decrypted.
  * @param api_HMD_log_in incoming event data port
  * @param api_HMD_log_out outgoing event data port
  */
pub fn compute_spec_Payload_Decrypted_guarantee(
  api_HMD_log_in: Option<Common::Log_Impl>,
  api_HMD_log_out: Option<Common::Log_Impl>) -> bool
{
  api_HMD_log_out.unwrap() != api_HMD_log_in.unwrap()
}

/** CEP-T-Guar: Top-level guarantee contracts for decryptor's compute entrypoint
  *
  * @param api_HMD_log_in incoming event data port
  * @param api_HMD_log_out outgoing event data port
  */
pub fn compute_CEP_T_Guar(
  api_HMD_log_in: Option<Common::Log_Impl>,
  api_HMD_log_out: Option<Common::Log_Impl>) -> bool
{
  let r0: bool = compute_spec_Payload_Decrypted_guarantee(api_HMD_log_in, api_HMD_log_out);

  return r0;
}

/** CEP-Post: Compute Entrypoint Post-Condition for decryptor
  *
  * @param api_HMD_log_in incoming event data port
  * @param api_HMD_log_out outgoing event data port
  */
pub fn compute_CEP_Post(
  api_HMD_log_in: Option<Common::Log_Impl>,
  api_HMD_log_out: Option<Common::Log_Impl>) -> bool
{
  // CEP-Guar: guarantee clauses of decryptor's compute entrypoint
  let r0: bool = compute_CEP_T_Guar(api_HMD_log_in, api_HMD_log_out);

  return r0;
}
