// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Place-assertion spec functions of property `datastorage_zeroize_cache` -- one per
//! point its decoration binds (unbound points carry `true`, design D5).

#![allow(non_snake_case)]
#![allow(unused_imports)]

use data::*;
use vstd::prelude::*;

use crate::assertions::*;
use crate::system_state::SystemState;

verus! {

/** property datastorage_zeroize_cache, bound 'after data_storage_1' (place after_data_storage_1)
  */
pub open spec fn sys_assert_datastorage_zeroize_cache_after_data_storage_1(st: SystemState) -> bool
{
  st.data_storage_zeroize_cmd ==> MATRICS_Model_Transformations::IS_ZEROIZED_ENCRYPTED_LOG_ARRAY_spec(st.data_storage_cache)
}

/** property datastorage_zeroize_cache, bound 'after data_storage_2' (place after_data_storage_2)
  */
pub open spec fn sys_assert_datastorage_zeroize_cache_after_data_storage_2(st: SystemState) -> bool
{
  st.data_storage_zeroize_cmd ==> MATRICS_Model_Transformations::IS_ZEROIZED_ENCRYPTED_LOG_ARRAY_spec(st.data_storage_cache)
}

/** property datastorage_zeroize_cache, bound 'after data_storage_3' (place after_data_storage_3)
  */
pub open spec fn sys_assert_datastorage_zeroize_cache_after_data_storage_3(st: SystemState) -> bool
{
  st.data_storage_zeroize_cmd ==> MATRICS_Model_Transformations::IS_ZEROIZED_ENCRYPTED_LOG_ARRAY_spec(st.data_storage_cache)
}

} // verus!
