#pragma once

#if __has_include("util.h")
#include <util.h>
#elif __has_include("libvmm/util/util.h")
#include <libvmm/util/util.h>
#elif __has_include("sddf/util/util.h")
#include <sddf/util/printf.h>
#include <sddf/util/util.h>
#define printf sddf_dprintf
#endif

#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun


bool put_HMD_log_out(const Common_Log_Impl *data);
bool HMD_log_in_is_empty(void);
bool get_HMD_log_in_poll(sb_event_counter_t *numDropped, Common_encryptedIncomingPayload_Impl *data);
bool get_HMD_log_in(Common_encryptedIncomingPayload_Impl *data);
