// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** Initialize EntryPointContract
  *
  * guarantee defaultAlert
  * @param alert_cmd post-state state variable
  */
pub fn initialize_defaultAlert(alert_cmd: bool) -> bool
{
  alert_cmd == false
}

/** IEP-Guar: Initialize Entrypoint for wifiDriver
  *
  * @param alert_cmd post-state state variable
  * @param api_HMD_log outgoing event data port
  * @param api_analysis_request outgoing event data port
  * @param api_wifiSend outgoing event data port
  */
pub fn initialize_IEP_Guar(
  alert_cmd: bool,
  api_HMD_log: Option<Common::encryptedIncomingPayload_Impl>,
  api_analysis_request: Option<Common::AnalysisRequest_Impl>,
  api_wifiSend: Option<Common::DummyMessage_Impl>) -> bool
{
  initialize_defaultAlert(alert_cmd)
}

/** IEP-Post: Initialize Entrypoint Post-Condition
  *
  * @param alert_cmd post-state state variable
  * @param api_HMD_log outgoing event data port
  * @param api_analysis_request outgoing event data port
  * @param api_wifiSend outgoing event data port
  */
pub fn initialize_IEP_Post(
  alert_cmd: bool,
  api_HMD_log: Option<Common::encryptedIncomingPayload_Impl>,
  api_analysis_request: Option<Common::AnalysisRequest_Impl>,
  api_wifiSend: Option<Common::DummyMessage_Impl>) -> bool
{
  initialize_IEP_Guar(alert_cmd, api_HMD_log, api_analysis_request, api_wifiSend)
}

/** Compute Entrypoint Contract
  *
  * guarantee alert_cmd_variable
  *   G: Once an alert command is seen, always stay alerted.
  * @param In_alert_cmd pre-state state variable
  * @param alert_cmd post-state state variable
  * @param api_alert incoming event data port
  */
pub fn compute_spec_alert_cmd_variable_guarantee(
  In_alert_cmd: bool,
  alert_cmd: bool,
  api_alert: Option<Common::DummyMessage_Impl>) -> bool
{
  (impliesL!(
    api_alert.is_some(),
    (alert_cmd == true))) &
    (impliesL!(
      (In_alert_cmd == true),
      (alert_cmd == true)))
}

/** Compute Entrypoint Contract
  *
  * guarantee Process_Report
  *   G: Stop outgoing communication once an alert has been received.
  * @param alert_cmd post-state state variable
  * @param api_analysis_report incoming event data port
  * @param api_wifiSend outgoing event data port
  */
pub fn compute_spec_Process_Report_guarantee(
  alert_cmd: bool,
  api_analysis_report: Option<Common::AnalysisReport_Impl>,
  api_wifiSend: Option<Common::DummyMessage_Impl>) -> bool
{
  if (api_analysis_report.is_some() & !alert_cmd) {
    api_wifiSend.is_some()
  } else {
    api_wifiSend.is_none()
  }
}

/** CEP-T-Guar: Top-level guarantee contracts for wifiDriver's compute entrypoint
  *
  * @param In_alert_cmd pre-state state variable
  * @param alert_cmd post-state state variable
  * @param api_alert incoming event data port
  * @param api_analysis_report incoming event data port
  * @param api_wifiSend outgoing event data port
  */
pub fn compute_CEP_T_Guar(
  In_alert_cmd: bool,
  alert_cmd: bool,
  api_alert: Option<Common::DummyMessage_Impl>,
  api_analysis_report: Option<Common::AnalysisReport_Impl>,
  api_wifiSend: Option<Common::DummyMessage_Impl>) -> bool
{
  let r0: bool = compute_spec_alert_cmd_variable_guarantee(In_alert_cmd, alert_cmd, api_alert);
  let r1: bool = compute_spec_Process_Report_guarantee(alert_cmd, api_analysis_report, api_wifiSend);

  return r0 && r1;
}

/** CEP-Post: Compute Entrypoint Post-Condition for wifiDriver
  *
  * @param In_alert_cmd pre-state state variable
  * @param alert_cmd post-state state variable
  * @param api_alert incoming event data port
  * @param api_analysis_report incoming event data port
  * @param api_wifiRecv incoming event data port
  * @param api_HMD_log outgoing event data port
  * @param api_analysis_request outgoing event data port
  * @param api_wifiSend outgoing event data port
  */
pub fn compute_CEP_Post(
  In_alert_cmd: bool,
  alert_cmd: bool,
  api_alert: Option<Common::DummyMessage_Impl>,
  api_analysis_report: Option<Common::AnalysisReport_Impl>,
  api_wifiRecv: Option<Common::IncomingWifiMessage_Impl>,
  api_HMD_log: Option<Common::encryptedIncomingPayload_Impl>,
  api_analysis_request: Option<Common::AnalysisRequest_Impl>,
  api_wifiSend: Option<Common::DummyMessage_Impl>) -> bool
{
  // CEP-Guar: guarantee clauses of wifiDriver's compute entrypoint
  let r0: bool = compute_CEP_T_Guar(In_alert_cmd, alert_cmd, api_alert, api_analysis_report, api_wifiSend);

  return r0;
}
