// Do not edit this file as it will be overwritten if codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_request_log: Option<Common::Request_Impl>,
  pub api_response_log_in: Option<Common::ResponseLog_Impl>
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_request_log(container.api_request_log);
  put_response_log_in(container.api_response_log_in);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(
  request_log: Option<Common::Request_Impl>,
  response_log_in: Option<Common::ResponseLog_Impl>)
{
  put_request_log(request_log);
  put_response_log_in(response_log_in);
}

/// setter for IN EventDataPort
pub fn put_request_log(value: Option<Common::Request_Impl>)
{
  *extern_api::IN_request_log.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_response_log_in(value: Option<Common::ResponseLog_Impl>)
{
  *extern_api::IN_response_log_in.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// getter for OUT EventDataPort
pub fn get_response_log_out() -> Option<Common::ResponseLog_Impl>
{
  return extern_api::OUT_response_log_out.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// getter for OUT EventPort
pub fn get_alert() -> Option<u8>
{
  return extern_api::OUT_alert.lock().unwrap_or_else(|e| e.into_inner()).clone()
}
