// Do not edit this file as it will be overwritten if codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** Compute Entrypoint Contract
  *
  * guarantee Payload_Encrypted
  *   G: Outgoing payload is encrypted.
  * @param api_analysis_report_in incoming event data port
  * @param api_analysis_report_out outgoing event data port
  */
pub fn compute_spec_Payload_Encrypted_guarantee(
  api_analysis_report_in: Option<Common::AnalysisReport_Impl>,
  api_analysis_report_out: Option<Common::AnalysisReport_Impl>) -> bool
{
  api_analysis_report_out.unwrap().payload != api_analysis_report_in.unwrap().payload
}

/** Compute Entrypoint Contract
  *
  * guarantee Header_Unencrypted
  *   G: Outgoing header is not encrypted.
  * @param api_analysis_report_in incoming event data port
  * @param api_analysis_report_out outgoing event data port
  */
pub fn compute_spec_Header_Unencrypted_guarantee(
  api_analysis_report_in: Option<Common::AnalysisReport_Impl>,
  api_analysis_report_out: Option<Common::AnalysisReport_Impl>) -> bool
{
  api_analysis_report_out.unwrap().header == api_analysis_report_in.unwrap().header
}

/** CEP-T-Guar: Top-level guarantee contracts for encryptor's compute entrypoint
  *
  * @param api_analysis_report_in incoming event data port
  * @param api_analysis_report_out outgoing event data port
  */
pub fn compute_CEP_T_Guar(
  api_analysis_report_in: Option<Common::AnalysisReport_Impl>,
  api_analysis_report_out: Option<Common::AnalysisReport_Impl>) -> bool
{
  let r0: bool = compute_spec_Payload_Encrypted_guarantee(api_analysis_report_in, api_analysis_report_out);
  let r1: bool = compute_spec_Header_Unencrypted_guarantee(api_analysis_report_in, api_analysis_report_out);

  return r0 && r1;
}

/** CEP-Post: Compute Entrypoint Post-Condition for encryptor
  *
  * @param api_analysis_report_in incoming event data port
  * @param api_analysis_report_out outgoing event data port
  */
pub fn compute_CEP_Post(
  api_analysis_report_in: Option<Common::AnalysisReport_Impl>,
  api_analysis_report_out: Option<Common::AnalysisReport_Impl>) -> bool
{
  // CEP-Guar: guarantee clauses of encryptor's compute entrypoint
  let r0: bool = compute_CEP_T_Guar(api_analysis_report_in, api_analysis_report_out);

  return r0;
}
