#!/bin/bash

# Modified from libvmm/tools/packrootfs


set -e

if [ $# -lt 2 ]; then
    echo "Usage: $0 <rootfs> <tmpdir> [-o output_rootfs] [--early_startup files...] [--startup files...] [--home files...] [--etc files...] [--nginx files ...]"
    exit 1
fi

which cpio >/dev/null
if [ "$?" != 0 ]; then
    echo "packrootfs: Please install cpio utility."
    exit 1
fi

rootfs=$1
tmpdir=$2
early_startup_files=()
startup_files=()
home_files=()
etc_files=()
nginx_files=()
output_rootfs=""

shift 2
while [[ $# -gt 0 ]]; do
    case $1 in
        --early_startup)
            shift
            while [[ $# -gt 0 ]] && ! [[ $1 == --* ]]; do
                early_startup_files+=("$1")
                shift
            done
            ;;
        --startup)
            shift
            while [[ $# -gt 0 ]] && ! [[ $1 == --* ]]; do
                startup_files+=("$1")
                shift
            done
            ;;
        --home)
            shift
            while [[ $# -gt 0 ]] && ! [[ $1 == --* ]]; do
                home_files+=("$1")
                shift
            done
            ;;
        --etc)
            shift
            while [[ $# -gt 0 ]] && ! [[ $1 == --* ]]; do
                etc_files+=("$1")
                shift
            done
            ;;
        --nginx)
            shift
            while [[ $# -gt 0 ]] && ! [[ $1 == --* ]]; do
                nginx_files+=("$1")
                shift
            done
            ;;
        -o)
            shift
            if [[ $# -gt 0 ]]; then
                output_rootfs=$1
                shift
            else
                echo "Error: -o option requires an argument."
                exit 1
            fi
            ;;
        *)
            echo "Unknown option $1"
            exit 1
            ;;
    esac
done

if [ -z "$output_rootfs" ]; then
    output_rootfs="rootfs_modified.cpio.gz"
fi

rm -rf "$tmpdir"
mkdir -p "$tmpdir"
mkdir -p "$tmpdir/root"
mkdir -p "$tmpdir/etc/nginx"
mkdir -p "$tmpdir/etc/init.d"

# Copy home files to /root
for file in "${home_files[@]}"; do
    cp -- "$file" "$tmpdir/root/$(basename "$file")"
    chmod +x "$tmpdir/root/$(basename "$file")"
done

# Copy early startup files to /etc/init.d and prefix with S45
for file in "${early_startup_files[@]}"; do
    cp -- "$file" "$tmpdir/etc/init.d/S45$(basename "$file")"
    chmod +x "$tmpdir/etc/init.d/S45$(basename "$file")"
done

# Copy startup files to /etc/init.d and prefix with S99
for file in "${startup_files[@]}"; do
    cp -- "$file" "$tmpdir/etc/init.d/S99$(basename "$file")"
    chmod +x "$tmpdir/etc/init.d/S99$(basename "$file")"
done

# Copy etc files to /etc
for file in "${etc_files[@]}"; do
    cp -- "$file" "$tmpdir/etc/$(basename "$file")"
done

# Copy startup files to /etc/nginx
for file in "${nginx_files[@]}"; do
    cp -- "$file" "$tmpdir/etc/nginx/$(basename "$file")"
    chmod +x "$tmpdir/etc/nginx/$(basename "$file")"
done

if [[ "$output_rootfs" == /* ]]; then
    final_output_path="$output_rootfs"
else
    final_output_path="$(pwd)/$output_rootfs"
fi

# Create CPIO from tmpdir and concatenate it with given rootfs, gzip result.
# This is required as we cannot unpack roofs on macOS.
({
    gunzip -dc "$rootfs";
    cd "$tmpdir" && find . | cpio --quiet -o -H newc
} | gzip > "$final_output_path")
