// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait cpuSw_dataManager_dataManager_Api {}

  pub trait cpuSw_dataManager_dataManager_Put_Api: cpuSw_dataManager_dataManager_Api {
    #[verifier::external_body]
    fn unverified_put_response_log(
      &mut self,
      value: Common::ResponseLog_Impl)
    {
      extern_api::unsafe_put_response_log(&value);
    }
  }

  pub trait cpuSw_dataManager_dataManager_Get_Api: cpuSw_dataManager_dataManager_Api {
    #[verifier::external_body]
    fn unverified_get_HMD_log(
      &mut self,
      value: &Ghost<Option<Common::Log_Impl>>) -> (res : Option<Common::Log_Impl>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_HMD_log();
    }

    #[verifier::external_body]
    fn unverified_get_request_log(
      &mut self,
      value: &Ghost<Option<Common::Request_Impl>>) -> (res : Option<Common::Request_Impl>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_request_log();
    }

    #[verifier::external_body]
    fn unverified_get_zeroize(
      &mut self,
      value: &Ghost<Option<u8>>) -> (res : bool)
      ensures
        res == value@.is_some(),
    {
      return extern_api::unsafe_get_zeroize();
    }
  }

  pub trait cpuSw_dataManager_dataManager_Full_Api: cpuSw_dataManager_dataManager_Put_Api + cpuSw_dataManager_dataManager_Get_Api {}

  pub struct cpuSw_dataManager_dataManager_Application_Api<API: cpuSw_dataManager_dataManager_Api> {
    pub api: API,

    pub ghost HMD_log: Option<Common::Log_Impl>,
    pub ghost request_log: Option<Common::Request_Impl>,
    pub ghost zeroize: Option<u8>,
    pub ghost response_log: Option<Common::ResponseLog_Impl>
  }

  impl<API: cpuSw_dataManager_dataManager_Put_Api> cpuSw_dataManager_dataManager_Application_Api<API> {
    pub fn put_response_log(
      &mut self,
      value: Common::ResponseLog_Impl)
      ensures
        old(self).HMD_log == self.HMD_log,
        old(self).request_log == self.request_log,
        self.response_log == Some(value),
        old(self).zeroize == self.zeroize,
    {
      self.api.unverified_put_response_log(value);
      self.response_log = Some(value);
    }
  }

  impl<API: cpuSw_dataManager_dataManager_Get_Api> cpuSw_dataManager_dataManager_Application_Api<API> {
    pub fn get_HMD_log(&mut self) -> (res : Option<Common::Log_Impl>)
      ensures
        old(self).HMD_log == self.HMD_log,
        res == self.HMD_log,
        old(self).request_log == self.request_log,
        old(self).response_log == self.response_log,
        old(self).zeroize == self.zeroize,
    {
      self.api.unverified_get_HMD_log(&Ghost(self.HMD_log))
    }
    pub fn get_request_log(&mut self) -> (res : Option<Common::Request_Impl>)
      ensures
        old(self).HMD_log == self.HMD_log,
        old(self).request_log == self.request_log,
        res == self.request_log,
        old(self).response_log == self.response_log,
        old(self).zeroize == self.zeroize,
    {
      self.api.unverified_get_request_log(&Ghost(self.request_log))
    }
    pub fn get_zeroize(&mut self) -> (res : bool)
      ensures
        old(self).HMD_log == self.HMD_log,
        old(self).request_log == self.request_log,
        old(self).response_log == self.response_log,
        old(self).zeroize == self.zeroize,
        res == self.zeroize.is_some(),
    {
      self.api.unverified_get_zeroize(&Ghost(self.zeroize))
    }
  }

  pub struct cpuSw_dataManager_dataManager_Initialization_Api;
  impl cpuSw_dataManager_dataManager_Api for cpuSw_dataManager_dataManager_Initialization_Api {}
  impl cpuSw_dataManager_dataManager_Put_Api for cpuSw_dataManager_dataManager_Initialization_Api {}

  pub const fn init_api() -> cpuSw_dataManager_dataManager_Application_Api<cpuSw_dataManager_dataManager_Initialization_Api> {
    return cpuSw_dataManager_dataManager_Application_Api {
      api: cpuSw_dataManager_dataManager_Initialization_Api {},

      HMD_log: None,
      request_log: None,
      zeroize: None,
      response_log: None
    }
  }

  pub struct cpuSw_dataManager_dataManager_Compute_Api;
  impl cpuSw_dataManager_dataManager_Api for cpuSw_dataManager_dataManager_Compute_Api {}
  impl cpuSw_dataManager_dataManager_Put_Api for cpuSw_dataManager_dataManager_Compute_Api {}
  impl cpuSw_dataManager_dataManager_Get_Api for cpuSw_dataManager_dataManager_Compute_Api {}
  impl cpuSw_dataManager_dataManager_Full_Api for cpuSw_dataManager_dataManager_Compute_Api {}

  pub const fn compute_api() -> cpuSw_dataManager_dataManager_Application_Api<cpuSw_dataManager_dataManager_Compute_Api> {
    return cpuSw_dataManager_dataManager_Application_Api {
      api: cpuSw_dataManager_dataManager_Compute_Api {},

      HMD_log: None,
      request_log: None,
      zeroize: None,
      response_log: None
    }
  }

}