#pragma once

#if __has_include("util.h")
#include <util.h>
#elif __has_include("libvmm/util/util.h")
#include <libvmm/util/util.h>
#elif __has_include("sddf/util/util.h")
#include <sddf/util/printf.h>
#include <sddf/util/util.h>
#define printf sddf_dprintf
#endif

#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun


bool wifiSendIn_is_empty(void);
bool get_wifiSendIn_poll(sb_event_counter_t *numDropped, Common_DummyMessage_Impl *data);
bool get_wifiSendIn(Common_DummyMessage_Impl *data);
bool put_wifiRecvOut(const Common_IncomingWifiMessage_Impl *data);
bool wifiRecvIn_is_empty(void);
bool get_wifiRecvIn_poll(sb_event_counter_t *numDropped, Common_IncomingWifiMessage_Impl *data);
bool get_wifiRecvIn(Common_IncomingWifiMessage_Impl *data);
bool put_wifiSendOut(const Common_DummyMessage_Impl *data);
