#include "cpuSw_dataManager_dataManager_dataManager.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

void cpuSw_dataManager_dataManager_dataManager_initialize(void);
void cpuSw_dataManager_dataManager_dataManager_notify(microkit_channel channel);
void cpuSw_dataManager_dataManager_dataManager_timeTriggered(void);

volatile sb_queue_Common_StoredLogFile_Impl_1_t *encrypted_log_queue_1;
volatile sb_queue_Common_AnalysisRequest_Impl_1_t *storage_request_queue_1;
volatile sb_queue_Common_AnalysisResponse_Impl_1_t *response_log_queue_1;
volatile sb_queue_Common_EncryptedAnalysisResponse_Impl_1_t *encrypted_response_queue_1;
sb_queue_Common_EncryptedAnalysisResponse_Impl_1_Recv_t encrypted_response_recv_queue;
volatile sb_queue_Common_AnalysisRequest_Impl_1_t *request_log_queue_1;
sb_queue_Common_AnalysisRequest_Impl_1_Recv_t request_log_recv_queue;
volatile sb_queue_Common_Log_Impl_1_t *HMD_log_queue_1;
sb_queue_Common_Log_Impl_1_Recv_t HMD_log_recv_queue;
volatile sb_queue_uint8_t_1_t *zeroize_queue_1;
sb_queue_uint8_t_1_Recv_t zeroize_recv_queue;

#define PORT_FROM_MON 0

bool put_encrypted_log(const Common_StoredLogFile_Impl *data) {
  sb_queue_Common_StoredLogFile_Impl_1_enqueue((sb_queue_Common_StoredLogFile_Impl_1_t *) encrypted_log_queue_1, (Common_StoredLogFile_Impl *) data);

  return true;
}

bool peek_encrypted_log(Common_StoredLogFile_Impl *data) {
  return sb_queue_Common_StoredLogFile_Impl_1_peek_latest((sb_queue_Common_StoredLogFile_Impl_1_t *) encrypted_log_queue_1, data);
}

bool put_storage_request(const Common_AnalysisRequest_Impl *data) {
  sb_queue_Common_AnalysisRequest_Impl_1_enqueue((sb_queue_Common_AnalysisRequest_Impl_1_t *) storage_request_queue_1, (Common_AnalysisRequest_Impl *) data);

  return true;
}

bool peek_storage_request(Common_AnalysisRequest_Impl *data) {
  return sb_queue_Common_AnalysisRequest_Impl_1_peek_latest((sb_queue_Common_AnalysisRequest_Impl_1_t *) storage_request_queue_1, data);
}

bool put_response_log(const Common_AnalysisResponse_Impl *data) {
  sb_queue_Common_AnalysisResponse_Impl_1_enqueue((sb_queue_Common_AnalysisResponse_Impl_1_t *) response_log_queue_1, (Common_AnalysisResponse_Impl *) data);

  return true;
}

bool peek_response_log(Common_AnalysisResponse_Impl *data) {
  return sb_queue_Common_AnalysisResponse_Impl_1_peek_latest((sb_queue_Common_AnalysisResponse_Impl_1_t *) response_log_queue_1, data);
}

bool encrypted_response_is_empty(void) {
  return sb_queue_Common_EncryptedAnalysisResponse_Impl_1_is_empty(&encrypted_response_recv_queue);
}

bool get_encrypted_response_poll(sb_event_counter_t *numDropped, Common_EncryptedAnalysisResponse_Impl *data) {
  return sb_queue_Common_EncryptedAnalysisResponse_Impl_1_dequeue((sb_queue_Common_EncryptedAnalysisResponse_Impl_1_Recv_t *) &encrypted_response_recv_queue, numDropped, data);
}

bool get_encrypted_response(Common_EncryptedAnalysisResponse_Impl *data) {
  sb_event_counter_t numDropped;
  return get_encrypted_response_poll (&numDropped, data);
}

bool peek_encrypted_response(Common_EncryptedAnalysisResponse_Impl *data) {
  sb_event_counter_t numDropped;
  return sb_queue_Common_EncryptedAnalysisResponse_Impl_1_peek((sb_queue_Common_EncryptedAnalysisResponse_Impl_1_Recv_t *) &encrypted_response_recv_queue, &numDropped, data);
}

bool request_log_is_empty(void) {
  return sb_queue_Common_AnalysisRequest_Impl_1_is_empty(&request_log_recv_queue);
}

bool get_request_log_poll(sb_event_counter_t *numDropped, Common_AnalysisRequest_Impl *data) {
  return sb_queue_Common_AnalysisRequest_Impl_1_dequeue((sb_queue_Common_AnalysisRequest_Impl_1_Recv_t *) &request_log_recv_queue, numDropped, data);
}

bool get_request_log(Common_AnalysisRequest_Impl *data) {
  sb_event_counter_t numDropped;
  return get_request_log_poll (&numDropped, data);
}

bool peek_request_log(Common_AnalysisRequest_Impl *data) {
  sb_event_counter_t numDropped;
  return sb_queue_Common_AnalysisRequest_Impl_1_peek((sb_queue_Common_AnalysisRequest_Impl_1_Recv_t *) &request_log_recv_queue, &numDropped, data);
}

bool HMD_log_is_empty(void) {
  return sb_queue_Common_Log_Impl_1_is_empty(&HMD_log_recv_queue);
}

bool get_HMD_log_poll(sb_event_counter_t *numDropped, Common_Log_Impl *data) {
  return sb_queue_Common_Log_Impl_1_dequeue((sb_queue_Common_Log_Impl_1_Recv_t *) &HMD_log_recv_queue, numDropped, data);
}

bool get_HMD_log(Common_Log_Impl *data) {
  sb_event_counter_t numDropped;
  return get_HMD_log_poll (&numDropped, data);
}

bool peek_HMD_log(Common_Log_Impl *data) {
  sb_event_counter_t numDropped;
  return sb_queue_Common_Log_Impl_1_peek((sb_queue_Common_Log_Impl_1_Recv_t *) &HMD_log_recv_queue, &numDropped, data);
}

bool zeroize_is_empty(void) {
  return sb_queue_uint8_t_1_is_empty(&zeroize_recv_queue);
}

bool get_zeroize_poll(sb_event_counter_t *numDropped) {
  uint8_t eventPortPayload;
  uint8_t *data = &eventPortPayload;
  return sb_queue_uint8_t_1_dequeue((sb_queue_uint8_t_1_Recv_t *) &zeroize_recv_queue, numDropped, data);
}

bool get_zeroize() {
  sb_event_counter_t numDropped;
  return get_zeroize_poll (&numDropped);
}

bool peek_zeroize() {
  uint8_t eventPortPayload;
  uint8_t *data = &eventPortPayload;
  sb_event_counter_t numDropped;
  return sb_queue_uint8_t_1_peek((sb_queue_uint8_t_1_Recv_t *) &zeroize_recv_queue, &numDropped, data);
}

void init(void) {
  printf("%s | INIT!\n", microkit_name);

  sb_queue_Common_StoredLogFile_Impl_1_init((sb_queue_Common_StoredLogFile_Impl_1_t *) encrypted_log_queue_1);

  sb_queue_Common_AnalysisRequest_Impl_1_init((sb_queue_Common_AnalysisRequest_Impl_1_t *) storage_request_queue_1);

  sb_queue_Common_AnalysisResponse_Impl_1_init((sb_queue_Common_AnalysisResponse_Impl_1_t *) response_log_queue_1);

  sb_queue_Common_EncryptedAnalysisResponse_Impl_1_Recv_init(&encrypted_response_recv_queue, (sb_queue_Common_EncryptedAnalysisResponse_Impl_1_t *) encrypted_response_queue_1);

  sb_queue_Common_AnalysisRequest_Impl_1_Recv_init(&request_log_recv_queue, (sb_queue_Common_AnalysisRequest_Impl_1_t *) request_log_queue_1);

  sb_queue_Common_Log_Impl_1_Recv_init(&HMD_log_recv_queue, (sb_queue_Common_Log_Impl_1_t *) HMD_log_queue_1);

  sb_queue_uint8_t_1_Recv_init(&zeroize_recv_queue, (sb_queue_uint8_t_1_t *) zeroize_queue_1);

  cpuSw_dataManager_dataManager_dataManager_initialize();

  microkit_notify(PORT_FROM_MON);
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      cpuSw_dataManager_dataManager_dataManager_timeTriggered();
      break;
    default:
      cpuSw_dataManager_dataManager_dataManager_notify(channel);
  }
}
