#include "cpuSw_wifiDriver_wifiDriver_wifiDriver.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

void cpuSw_wifiDriver_wifiDriver_wifiDriver_initialize(void);
void cpuSw_wifiDriver_wifiDriver_wifiDriver_notify(microkit_channel channel);
void cpuSw_wifiDriver_wifiDriver_wifiDriver_timeTriggered(void);

volatile sb_queue_Common_AnalysisReport_Impl_1_t *analysis_report_queue_1;
sb_queue_Common_AnalysisReport_Impl_1_Recv_t analysis_report_recv_queue;
volatile sb_queue_Common_DummyMessage_Impl_1_t *alert_queue_1;
sb_queue_Common_DummyMessage_Impl_1_Recv_t alert_recv_queue;
volatile sb_queue_Common_DummyMessage_Impl_1_t *wifiSend_queue_1;
volatile sb_queue_Common_encryptedIncomingPayload_Impl_1_t *HMD_log_queue_1;
volatile sb_queue_Common_AnalysisRequest_Impl_1_t *analysis_request_queue_1;
volatile sb_queue_Common_IncomingWifiMessage_Impl_1_t *wifiRecv_queue_1;
sb_queue_Common_IncomingWifiMessage_Impl_1_Recv_t wifiRecv_recv_queue;

#define PORT_FROM_MON 0

bool analysis_report_is_empty(void) {
  return sb_queue_Common_AnalysisReport_Impl_1_is_empty(&analysis_report_recv_queue);
}

bool get_analysis_report_poll(sb_event_counter_t *numDropped, Common_AnalysisReport_Impl *data) {
  return sb_queue_Common_AnalysisReport_Impl_1_dequeue((sb_queue_Common_AnalysisReport_Impl_1_Recv_t *) &analysis_report_recv_queue, numDropped, data);
}

bool get_analysis_report(Common_AnalysisReport_Impl *data) {
  sb_event_counter_t numDropped;
  return get_analysis_report_poll (&numDropped, data);
}

bool alert_is_empty(void) {
  return sb_queue_Common_DummyMessage_Impl_1_is_empty(&alert_recv_queue);
}

bool get_alert_poll(sb_event_counter_t *numDropped, Common_DummyMessage_Impl *data) {
  return sb_queue_Common_DummyMessage_Impl_1_dequeue((sb_queue_Common_DummyMessage_Impl_1_Recv_t *) &alert_recv_queue, numDropped, data);
}

bool get_alert(Common_DummyMessage_Impl *data) {
  sb_event_counter_t numDropped;
  return get_alert_poll (&numDropped, data);
}

bool put_wifiSend(const Common_DummyMessage_Impl *data) {
  sb_queue_Common_DummyMessage_Impl_1_enqueue((sb_queue_Common_DummyMessage_Impl_1_t *) wifiSend_queue_1, (Common_DummyMessage_Impl *) data);

  return true;
}

bool put_HMD_log(const Common_encryptedIncomingPayload_Impl *data) {
  sb_queue_Common_encryptedIncomingPayload_Impl_1_enqueue((sb_queue_Common_encryptedIncomingPayload_Impl_1_t *) HMD_log_queue_1, (Common_encryptedIncomingPayload_Impl *) data);

  return true;
}

bool put_analysis_request(const Common_AnalysisRequest_Impl *data) {
  sb_queue_Common_AnalysisRequest_Impl_1_enqueue((sb_queue_Common_AnalysisRequest_Impl_1_t *) analysis_request_queue_1, (Common_AnalysisRequest_Impl *) data);

  return true;
}

bool wifiRecv_is_empty(void) {
  return sb_queue_Common_IncomingWifiMessage_Impl_1_is_empty(&wifiRecv_recv_queue);
}

bool get_wifiRecv_poll(sb_event_counter_t *numDropped, Common_IncomingWifiMessage_Impl *data) {
  return sb_queue_Common_IncomingWifiMessage_Impl_1_dequeue((sb_queue_Common_IncomingWifiMessage_Impl_1_Recv_t *) &wifiRecv_recv_queue, numDropped, data);
}

bool get_wifiRecv(Common_IncomingWifiMessage_Impl *data) {
  sb_event_counter_t numDropped;
  return get_wifiRecv_poll (&numDropped, data);
}

void init(void) {
  printf("%s | INIT!\n", microkit_name);

  sb_queue_Common_AnalysisReport_Impl_1_Recv_init(&analysis_report_recv_queue, (sb_queue_Common_AnalysisReport_Impl_1_t *) analysis_report_queue_1);

  sb_queue_Common_DummyMessage_Impl_1_Recv_init(&alert_recv_queue, (sb_queue_Common_DummyMessage_Impl_1_t *) alert_queue_1);

  sb_queue_Common_DummyMessage_Impl_1_init((sb_queue_Common_DummyMessage_Impl_1_t *) wifiSend_queue_1);

  sb_queue_Common_encryptedIncomingPayload_Impl_1_init((sb_queue_Common_encryptedIncomingPayload_Impl_1_t *) HMD_log_queue_1);

  sb_queue_Common_AnalysisRequest_Impl_1_init((sb_queue_Common_AnalysisRequest_Impl_1_t *) analysis_request_queue_1);

  sb_queue_Common_IncomingWifiMessage_Impl_1_Recv_init(&wifiRecv_recv_queue, (sb_queue_Common_IncomingWifiMessage_Impl_1_t *) wifiRecv_queue_1);

  cpuSw_wifiDriver_wifiDriver_wifiDriver_initialize();

  microkit_notify(PORT_FROM_MON);
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      cpuSw_wifiDriver_wifiDriver_wifiDriver_timeTriggered();
      break;
    default:
      cpuSw_wifiDriver_wifiDriver_wifiDriver_notify(channel);
  }
}
