/**
 * Copyright (c) 2024, Collins Aerospace.
 * Developed with the sponsorship of Defense Advanced Research Projects Agency (DARPA).
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this data, 
 * including any software or models in source or binary form, as well as any drawings, specifications, 
 * and documentation (collectively "the Data"), to deal in the Data without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Data, and to permit persons to whom the Data is furnished to do so, 
 * subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or 
 * substantial portions of the Data.
 * 
 * THE DATA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT 
 * LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
 * IN NO EVENT SHALL THE AUTHORS, SPONSORS, DEVELOPERS, CONTRIBUTORS, OR COPYRIGHT HOLDERS BE LIABLE 
 * FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE DATA OR THE USE OR OTHER DEALINGS IN THE DATA.
 * 
 * Generated by Xtext version 2.33.0.
 */
package com.collins.trustedmethods.matrics.soar.soar;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pref Specifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.collins.trustedmethods.matrics.soar.soar.PrefSpecifier#getUnaryPref <em>Unary Pref</em>}</li>
 *   <li>{@link com.collins.trustedmethods.matrics.soar.soar.PrefSpecifier#getUnaryOrBinaryPref <em>Unary Or Binary Pref</em>}</li>
 *   <li>{@link com.collins.trustedmethods.matrics.soar.soar.PrefSpecifier#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see com.collins.trustedmethods.matrics.soar.soar.SoarPackage#getPrefSpecifier()
 * @model
 * @generated
 */
public interface PrefSpecifier extends EObject
{
  /**
   * Returns the value of the '<em><b>Unary Pref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unary Pref</em>' attribute.
   * @see #setUnaryPref(String)
   * @see com.collins.trustedmethods.matrics.soar.soar.SoarPackage#getPrefSpecifier_UnaryPref()
   * @model
   * @generated
   */
  String getUnaryPref();

  /**
   * Sets the value of the '{@link com.collins.trustedmethods.matrics.soar.soar.PrefSpecifier#getUnaryPref <em>Unary Pref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unary Pref</em>' attribute.
   * @see #getUnaryPref()
   * @generated
   */
  void setUnaryPref(String value);

  /**
   * Returns the value of the '<em><b>Unary Or Binary Pref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unary Or Binary Pref</em>' attribute.
   * @see #setUnaryOrBinaryPref(String)
   * @see com.collins.trustedmethods.matrics.soar.soar.SoarPackage#getPrefSpecifier_UnaryOrBinaryPref()
   * @model
   * @generated
   */
  String getUnaryOrBinaryPref();

  /**
   * Sets the value of the '{@link com.collins.trustedmethods.matrics.soar.soar.PrefSpecifier#getUnaryOrBinaryPref <em>Unary Or Binary Pref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unary Or Binary Pref</em>' attribute.
   * @see #getUnaryOrBinaryPref()
   * @generated
   */
  void setUnaryOrBinaryPref(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Value)
   * @see com.collins.trustedmethods.matrics.soar.soar.SoarPackage#getPrefSpecifier_Value()
   * @model containment="true"
   * @generated
   */
  Value getValue();

  /**
   * Sets the value of the '{@link com.collins.trustedmethods.matrics.soar.soar.PrefSpecifier#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Value value);

} // PrefSpecifier
