/**
 * Copyright (c) 2023, Collins Aerospace.
 * Developed with the sponsorship of Defense Advanced Research Projects Agency (DARPA).
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this data, 
 * including any software or models in source or binary form, as well as any drawings, specifications, 
 * and documentation (collectively "the Data"), to deal in the Data without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Data, and to permit persons to whom the Data is furnished to do so, 
 * subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or 
 * substantial portions of the Data.
 * 
 * THE DATA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT 
 * LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
 * IN NO EVENT SHALL THE AUTHORS, SPONSORS, DEVELOPERS, CONTRIBUTORS, OR COPYRIGHT HOLDERS BE LIABLE 
 * FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE DATA OR THE USE OR OTHER DEALINGS IN THE DATA.
 * 
 * Generated by Xtext version 2.25.0.
 */
package com.collins.trustedmethods.matrics.soar.soar;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.collins.trustedmethods.matrics.soar.soar.SoarPackage
 * @generated
 */
public interface SoarFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SoarFactory eINSTANCE = com.collins.trustedmethods.matrics.soar.soar.impl.SoarFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Annex Library</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Annex Library</em>'.
   * @generated
   */
  SoarAnnexLibrary createSoarAnnexLibrary();

  /**
   * Returns a new object of class '<em>Annex Subclause</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Annex Subclause</em>'.
   * @generated
   */
  SoarAnnexSubclause createSoarAnnexSubclause();

  /**
   * Returns a new object of class '<em>Production</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Production</em>'.
   * @generated
   */
  SoarProduction createSoarProduction();

  /**
   * Returns a new object of class '<em>State Imp Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State Imp Condition</em>'.
   * @generated
   */
  StateImpCondition createStateImpCondition();

  /**
   * Returns a new object of class '<em>Attr Value Test</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attr Value Test</em>'.
   * @generated
   */
  AttrValueTest createAttrValueTest();

  /**
   * Returns a new object of class '<em>Condition Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Condition Expr</em>'.
   * @generated
   */
  ConditionExpr createConditionExpr();

  /**
   * Returns a new object of class '<em>Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr</em>'.
   * @generated
   */
  Expr createExpr();

  /**
   * Returns a new object of class '<em>Action Side Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action Side Expr</em>'.
   * @generated
   */
  ActionSideExpr createActionSideExpr();

  /**
   * Returns a new object of class '<em>State Imp Cond</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State Imp Cond</em>'.
   * @generated
   */
  StateImpCond createStateImpCond();

  /**
   * Returns a new object of class '<em>Binary Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Binary Expr</em>'.
   * @generated
   */
  BinaryExpr createBinaryExpr();

  /**
   * Returns a new object of class '<em>Unary Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Unary Expr</em>'.
   * @generated
   */
  UnaryExpr createUnaryExpr();

  /**
   * Returns a new object of class '<em>Conjunct Test Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conjunct Test Expr</em>'.
   * @generated
   */
  ConjunctTestExpr createConjunctTestExpr();

  /**
   * Returns a new object of class '<em>Multi Val Test Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Multi Val Test Expr</em>'.
   * @generated
   */
  MultiValTestExpr createMultiValTestExpr();

  /**
   * Returns a new object of class '<em>Disjunct Test Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Disjunct Test Expr</em>'.
   * @generated
   */
  DisjunctTestExpr createDisjunctTestExpr();

  /**
   * Returns a new object of class '<em>Sym Const Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sym Const Expr</em>'.
   * @generated
   */
  SymConstExpr createSymConstExpr();

  /**
   * Returns a new object of class '<em>Const String Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Const String Expr</em>'.
   * @generated
   */
  ConstStringExpr createConstStringExpr();

  /**
   * Returns a new object of class '<em>String Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Expr</em>'.
   * @generated
   */
  StringExpr createStringExpr();

  /**
   * Returns a new object of class '<em>Pref Specifier Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pref Specifier Expr</em>'.
   * @generated
   */
  PrefSpecifierExpr createPrefSpecifierExpr();

  /**
   * Returns a new object of class '<em>Crlf Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Crlf Expr</em>'.
   * @generated
   */
  CrlfExpr createCrlfExpr();

  /**
   * Returns a new object of class '<em>Comma Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Comma Expr</em>'.
   * @generated
   */
  CommaExpr createCommaExpr();

  /**
   * Returns a new object of class '<em>Paren Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Paren Expr</em>'.
   * @generated
   */
  ParenExpr createParenExpr();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  SoarPackage getSoarPackage();

} //SoarFactory
