// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_btRecv: Option<Common::DummyMessage_Impl>
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_btRecv(container.api_btRecv);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(btRecv: Option<Common::DummyMessage_Impl>)
{
  put_btRecv(btRecv);
}

/// setter for IN EventDataPort
pub fn put_btRecv(value: Option<Common::DummyMessage_Impl>)
{
  *extern_api::IN_btRecv.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// getter for OUT EventDataPort
pub fn get_btSend() -> Option<Common::DummyMessage_Impl>
{
  return extern_api::OUT_btSend.lock().unwrap_or_else(|e| e.into_inner()).clone()
}
