# Do not edit this file as it will be overwritten if codegen is rerun

MICROKIT_TOOL ?= $(MICROKIT_SDK)/bin/microkit

CFLAGS := -mcpu=$(CPU) \
	-mstrict-align \
	-ffreestanding \
	-nostdlib \
	-g3 \
	-O3 \
	-Wall -Wno-unused-function -Werror -Wno-unused-command-line-argument \
	-I$(MICROKIT_BOARD_DIR)/include \
	-target $(TARGET)

LDFLAGS := -L$(MICROKIT_BOARD_DIR)/lib
LIBS := --start-group -lmicrokit -Tmicrokit.ld --end-group

MSD ?= microkit.system

IMAGES := cpuSw_btDriver_btDriver.elf cpuSw_btDriver_btDriver_MON.elf cpuSw_usbDriver_usbDriver.elf cpuSw_usbDriver_usbDriver_MON.elf cpuSw_dataManager_dataManager.elf cpuSw_dataManager_dataManager_MON.elf cpuSw_dataAnalysis_dataAnalysis.elf cpuSw_dataAnalysis_dataAnalysis_MON.elf cpuSw_decryptor_decryptor.elf cpuSw_decryptor_decryptor_MON.elf cpuSw_encryptor_encryptor.elf cpuSw_encryptor_encryptor_MON.elf cpuSw_logMonitor_logMonitor.elf cpuSw_logMonitor_logMonitor_MON.elf cpuSw_reportMonitor_reportMonitor.elf cpuSw_reportMonitor_reportMonitor_MON.elf cpuSw_firewall_firewall.elf cpuSw_firewall_firewall_MON.elf cpuSw_wifiDriver_wifiDriver_wifiDriver.elf cpuSw_wifiDriver_wifiDriver_wifiDriver_MON.elf cpuSw_wifiDriver_wifiDriverVM_wifiDriver.elf cpuSw_wifiDriver_wifiDriverVM_wifiDriver_MON.elf pacer.elf
IMAGE_FILE = loader.img
REPORT_FILE = report.txt

UTIL_OBJS = printf.o util.o

TYPES_DIR = $(TOP_DIR)/types
TYPE_OBJS := $(TOP_DIR)/build/sb_queue_Common_DummyMessage_Impl_1.o $(TOP_DIR)/build/sb_queue_Common_ResponseLog_Impl_1.o $(TOP_DIR)/build/sb_queue_Common_Request_Impl_1.o $(TOP_DIR)/build/sb_queue_Common_AnalysisReport_Impl_1.o $(TOP_DIR)/build/sb_queue_Common_Log_Impl_1.o $(TOP_DIR)/build/sb_queue_uint8_t_1.o $(TOP_DIR)/build/sb_queue_Common_AnalysisRequest_Impl_1.o

# exporting TOP_TYPES_INCLUDE in case other makefiles need it
export TOP_TYPES_INCLUDE = -I$(TYPES_DIR)/include

TOP_INCLUDE = $(TOP_TYPES_INCLUDE) -I$(TOP_DIR)/util/include

all: $(IMAGE_FILE)
	CHECK_FLAGS_BOARD_MD5:=.board_cflags-$(shell echo -- ${CFLAGS} ${MICROKIT_BOARD} ${MICROKIT_CONFIG}| shasum | sed 's/ *-//')

${CHECK_FLAGS_BOARD_MD5}:
	-rm -f .board_cflags-*
	touch $@

%.o: ${TOP_DIR}/util/src/%.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ -I$(TOP_DIR)/util/include

$(TOP_DIR)/build/sb_queue_Common_DummyMessage_Impl_1.o: $(TOP_DIR)/types/src/sb_queue_Common_DummyMessage_Impl_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


$(TOP_DIR)/build/sb_queue_Common_ResponseLog_Impl_1.o: $(TOP_DIR)/types/src/sb_queue_Common_ResponseLog_Impl_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


$(TOP_DIR)/build/sb_queue_Common_Request_Impl_1.o: $(TOP_DIR)/types/src/sb_queue_Common_Request_Impl_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


$(TOP_DIR)/build/sb_queue_Common_AnalysisReport_Impl_1.o: $(TOP_DIR)/types/src/sb_queue_Common_AnalysisReport_Impl_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


$(TOP_DIR)/build/sb_queue_Common_Log_Impl_1.o: $(TOP_DIR)/types/src/sb_queue_Common_Log_Impl_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


$(TOP_DIR)/build/sb_queue_uint8_t_1.o: $(TOP_DIR)/types/src/sb_queue_uint8_t_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


$(TOP_DIR)/build/sb_queue_Common_AnalysisRequest_Impl_1.o: $(TOP_DIR)/types/src/sb_queue_Common_AnalysisRequest_Impl_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


# monitor
cpuSw_btDriver_btDriver_MON.o: $(TOP_DIR)/components/cpuSw_btDriver_btDriver/src/cpuSw_btDriver_btDriver_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_btDriver_btDriver/include

# user code
cpuSw_btDriver_btDriver_rust:
	make -C ${CRATES_DIR}/cpuSw_btDriver_btDriver $(RUST_MAKE_TARGET)

cpuSw_btDriver_btDriver.o: $(TOP_DIR)/components/cpuSw_btDriver_btDriver/src/cpuSw_btDriver_btDriver.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_btDriver_btDriver/include

# monitor
cpuSw_usbDriver_usbDriver_MON.o: $(TOP_DIR)/components/cpuSw_usbDriver_usbDriver/src/cpuSw_usbDriver_usbDriver_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_usbDriver_usbDriver/include

# user code
cpuSw_usbDriver_usbDriver_rust:
	make -C ${CRATES_DIR}/cpuSw_usbDriver_usbDriver $(RUST_MAKE_TARGET)

cpuSw_usbDriver_usbDriver.o: $(TOP_DIR)/components/cpuSw_usbDriver_usbDriver/src/cpuSw_usbDriver_usbDriver.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_usbDriver_usbDriver/include

# monitor
cpuSw_dataManager_dataManager_MON.o: $(TOP_DIR)/components/cpuSw_dataManager_dataManager/src/cpuSw_dataManager_dataManager_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_dataManager_dataManager/include

# user code
cpuSw_dataManager_dataManager_rust:
	make -C ${CRATES_DIR}/cpuSw_dataManager_dataManager $(RUST_MAKE_TARGET)

cpuSw_dataManager_dataManager.o: $(TOP_DIR)/components/cpuSw_dataManager_dataManager/src/cpuSw_dataManager_dataManager.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_dataManager_dataManager/include

# monitor
cpuSw_dataAnalysis_dataAnalysis_MON.o: $(TOP_DIR)/components/cpuSw_dataAnalysis_dataAnalysis/src/cpuSw_dataAnalysis_dataAnalysis_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_dataAnalysis_dataAnalysis/include

# user code
cpuSw_dataAnalysis_dataAnalysis_rust:
	make -C ${CRATES_DIR}/cpuSw_dataAnalysis_dataAnalysis $(RUST_MAKE_TARGET)

cpuSw_dataAnalysis_dataAnalysis.o: $(TOP_DIR)/components/cpuSw_dataAnalysis_dataAnalysis/src/cpuSw_dataAnalysis_dataAnalysis.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_dataAnalysis_dataAnalysis/include

# monitor
cpuSw_decryptor_decryptor_MON.o: $(TOP_DIR)/components/cpuSw_decryptor_decryptor/src/cpuSw_decryptor_decryptor_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_decryptor_decryptor/include

# user code
cpuSw_decryptor_decryptor_rust:
	make -C ${CRATES_DIR}/cpuSw_decryptor_decryptor $(RUST_MAKE_TARGET)

cpuSw_decryptor_decryptor.o: $(TOP_DIR)/components/cpuSw_decryptor_decryptor/src/cpuSw_decryptor_decryptor.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_decryptor_decryptor/include

# monitor
cpuSw_encryptor_encryptor_MON.o: $(TOP_DIR)/components/cpuSw_encryptor_encryptor/src/cpuSw_encryptor_encryptor_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_encryptor_encryptor/include

# user code
cpuSw_encryptor_encryptor_rust:
	make -C ${CRATES_DIR}/cpuSw_encryptor_encryptor $(RUST_MAKE_TARGET)

cpuSw_encryptor_encryptor.o: $(TOP_DIR)/components/cpuSw_encryptor_encryptor/src/cpuSw_encryptor_encryptor.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_encryptor_encryptor/include

# monitor
cpuSw_logMonitor_logMonitor_MON.o: $(TOP_DIR)/components/cpuSw_logMonitor_logMonitor/src/cpuSw_logMonitor_logMonitor_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_logMonitor_logMonitor/include

# user code
cpuSw_logMonitor_logMonitor_rust:
	make -C ${CRATES_DIR}/cpuSw_logMonitor_logMonitor $(RUST_MAKE_TARGET)

cpuSw_logMonitor_logMonitor.o: $(TOP_DIR)/components/cpuSw_logMonitor_logMonitor/src/cpuSw_logMonitor_logMonitor.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_logMonitor_logMonitor/include

# monitor
cpuSw_reportMonitor_reportMonitor_MON.o: $(TOP_DIR)/components/cpuSw_reportMonitor_reportMonitor/src/cpuSw_reportMonitor_reportMonitor_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_reportMonitor_reportMonitor/include

# user code
cpuSw_reportMonitor_reportMonitor_rust:
	make -C ${CRATES_DIR}/cpuSw_reportMonitor_reportMonitor $(RUST_MAKE_TARGET)

cpuSw_reportMonitor_reportMonitor.o: $(TOP_DIR)/components/cpuSw_reportMonitor_reportMonitor/src/cpuSw_reportMonitor_reportMonitor.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_reportMonitor_reportMonitor/include

# monitor
cpuSw_firewall_firewall_MON.o: $(TOP_DIR)/components/cpuSw_firewall_firewall/src/cpuSw_firewall_firewall_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_firewall_firewall/include

# user code
cpuSw_firewall_firewall_rust:
	make -C ${CRATES_DIR}/cpuSw_firewall_firewall $(RUST_MAKE_TARGET)

cpuSw_firewall_firewall.o: $(TOP_DIR)/components/cpuSw_firewall_firewall/src/cpuSw_firewall_firewall.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_firewall_firewall/include

# monitor
cpuSw_wifiDriver_wifiDriver_wifiDriver_MON.o: $(TOP_DIR)/components/cpuSw_wifiDriver_wifiDriver_wifiDriver/src/cpuSw_wifiDriver_wifiDriver_wifiDriver_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_wifiDriver_wifiDriver_wifiDriver/include

# user code
cpuSw_wifiDriver_wifiDriver_wifiDriver_rust:
	make -C ${CRATES_DIR}/cpuSw_wifiDriver_wifiDriver_wifiDriver $(RUST_MAKE_TARGET)

cpuSw_wifiDriver_wifiDriver_wifiDriver.o: $(TOP_DIR)/components/cpuSw_wifiDriver_wifiDriver_wifiDriver/src/cpuSw_wifiDriver_wifiDriver_wifiDriver.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_wifiDriver_wifiDriver_wifiDriver/include

# monitor
cpuSw_wifiDriver_wifiDriverVM_wifiDriver_MON.o: $(TOP_DIR)/components/cpuSw_wifiDriver_wifiDriverVM_wifiDriver/src/cpuSw_wifiDriver_wifiDriverVM_wifiDriver_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cpuSw_wifiDriver_wifiDriverVM_wifiDriver/include

# cpuSw_wifiDriver_wifiDriverVM_wifiDriver.a contains a VM
.PHONY: cpuSw_wifiDriver_wifiDriverVM_wifiDriver.a
cpuSw_wifiDriver_wifiDriverVM_wifiDriver.a:
ifeq (, $(wildcard $(TOP_DIR)/components/cpuSw_wifiDriver_wifiDriverVM_wifiDriver/board/$(MICROKIT_BOARD)/Makefile))
	$(error Didn't find: $(TOP_DIR)/components/cpuSw_wifiDriver_wifiDriverVM_wifiDriver/board/$(MICROKIT_BOARD)/Makefile);
endif
	mkdir -p $(TOP_DIR)/components/cpuSw_wifiDriver_wifiDriverVM_wifiDriver/build
	cp $(TOP_DIR)/components/cpuSw_wifiDriver_wifiDriverVM_wifiDriver/board/${MICROKIT_BOARD}/Makefile $(TOP_DIR)/components/cpuSw_wifiDriver_wifiDriverVM_wifiDriver/build
	make -C $(TOP_DIR)/components/cpuSw_wifiDriver_wifiDriverVM_wifiDriver/build


pacer.o: $(TOP_DIR)/components/pacer/src/pacer.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ -I$(TOP_INCLUDE)

cpuSw_btDriver_btDriver_MON.elf: cpuSw_btDriver_btDriver_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

cpuSw_btDriver_btDriver.elf: $(UTIL_OBJS) $(TYPE_OBJS) cpuSw_btDriver_btDriver_rust cpuSw_btDriver_btDriver.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/cpuSw_btDriver_btDriver/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lcpuSw_btDriver_btDriver -o $@

cpuSw_usbDriver_usbDriver_MON.elf: cpuSw_usbDriver_usbDriver_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

cpuSw_usbDriver_usbDriver.elf: $(UTIL_OBJS) $(TYPE_OBJS) cpuSw_usbDriver_usbDriver_rust cpuSw_usbDriver_usbDriver.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/cpuSw_usbDriver_usbDriver/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lcpuSw_usbDriver_usbDriver -o $@

cpuSw_dataManager_dataManager_MON.elf: cpuSw_dataManager_dataManager_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

cpuSw_dataManager_dataManager.elf: $(UTIL_OBJS) $(TYPE_OBJS) cpuSw_dataManager_dataManager_rust cpuSw_dataManager_dataManager.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/cpuSw_dataManager_dataManager/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lcpuSw_dataManager_dataManager -o $@

cpuSw_dataAnalysis_dataAnalysis_MON.elf: cpuSw_dataAnalysis_dataAnalysis_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

cpuSw_dataAnalysis_dataAnalysis.elf: $(UTIL_OBJS) $(TYPE_OBJS) cpuSw_dataAnalysis_dataAnalysis_rust cpuSw_dataAnalysis_dataAnalysis.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/cpuSw_dataAnalysis_dataAnalysis/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lcpuSw_dataAnalysis_dataAnalysis -o $@

cpuSw_decryptor_decryptor_MON.elf: cpuSw_decryptor_decryptor_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

cpuSw_decryptor_decryptor.elf: $(UTIL_OBJS) $(TYPE_OBJS) cpuSw_decryptor_decryptor_rust cpuSw_decryptor_decryptor.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/cpuSw_decryptor_decryptor/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lcpuSw_decryptor_decryptor -o $@

cpuSw_encryptor_encryptor_MON.elf: cpuSw_encryptor_encryptor_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

cpuSw_encryptor_encryptor.elf: $(UTIL_OBJS) $(TYPE_OBJS) cpuSw_encryptor_encryptor_rust cpuSw_encryptor_encryptor.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/cpuSw_encryptor_encryptor/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lcpuSw_encryptor_encryptor -o $@

cpuSw_logMonitor_logMonitor_MON.elf: cpuSw_logMonitor_logMonitor_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

cpuSw_logMonitor_logMonitor.elf: $(UTIL_OBJS) $(TYPE_OBJS) cpuSw_logMonitor_logMonitor_rust cpuSw_logMonitor_logMonitor.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/cpuSw_logMonitor_logMonitor/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lcpuSw_logMonitor_logMonitor -o $@

cpuSw_reportMonitor_reportMonitor_MON.elf: cpuSw_reportMonitor_reportMonitor_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

cpuSw_reportMonitor_reportMonitor.elf: $(UTIL_OBJS) $(TYPE_OBJS) cpuSw_reportMonitor_reportMonitor_rust cpuSw_reportMonitor_reportMonitor.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/cpuSw_reportMonitor_reportMonitor/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lcpuSw_reportMonitor_reportMonitor -o $@

cpuSw_firewall_firewall_MON.elf: cpuSw_firewall_firewall_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

cpuSw_firewall_firewall.elf: $(UTIL_OBJS) $(TYPE_OBJS) cpuSw_firewall_firewall_rust cpuSw_firewall_firewall.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/cpuSw_firewall_firewall/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lcpuSw_firewall_firewall -o $@

cpuSw_wifiDriver_wifiDriver_wifiDriver_MON.elf: cpuSw_wifiDriver_wifiDriver_wifiDriver_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

cpuSw_wifiDriver_wifiDriver_wifiDriver.elf: $(UTIL_OBJS) $(TYPE_OBJS) cpuSw_wifiDriver_wifiDriver_wifiDriver_rust cpuSw_wifiDriver_wifiDriver_wifiDriver.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/cpuSw_wifiDriver_wifiDriver_wifiDriver/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lcpuSw_wifiDriver_wifiDriver_wifiDriver -o $@

cpuSw_wifiDriver_wifiDriverVM_wifiDriver_MON.elf: cpuSw_wifiDriver_wifiDriverVM_wifiDriver_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

cpuSw_wifiDriver_wifiDriverVM_wifiDriver.elf: $(TYPE_OBJS) cpuSw_wifiDriver_wifiDriverVM_wifiDriver.a
	$(LD) $(LDFLAGS) $^ --start-group -lmicrokit -Tmicrokit.ld cpuSw_wifiDriver_wifiDriverVM_wifiDriver.a --end-group -o $@

pacer.elf: $(UTIL_OBJS) $(TYPE_OBJS) pacer.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

$(IMAGE_FILE): $(IMAGES) $(TOP_DIR)/$(MSD)
	xmllint --xinclude $(TOP_DIR)/$(MSD) -o $(TOP_BUILD_DIR)/$(MSD).merged
	$(MICROKIT_TOOL) $(TOP_BUILD_DIR)/$(MSD).merged --search-path $(TOP_BUILD_DIR) --board $(MICROKIT_BOARD) --config $(MICROKIT_CONFIG) -o $(IMAGE_FILE) -r $(REPORT_FILE)


qemu: $(IMAGE_FILE)
	$(QEMU) -machine virt,virtualization=on,highmem=off,secure=off,gic-version=2 \
                -cpu cortex-a53 \
                -serial mon:stdio \
                -device loader,file=$(IMAGE_FILE),addr=0x70000000,cpu-num=0 \
                -m 2G \
                -nographic \
			 -global virtio-mmio.force-legacy=false \
			 -netdev user,id=mynet0  \
 			 -device virtio-net-device,netdev=mynet0

clean::
	rm -f *.o

test:: 
	make -C ${CRATES_DIR}/cpuSw_btDriver_btDriver test
	make -C ${CRATES_DIR}/cpuSw_usbDriver_usbDriver test
	make -C ${CRATES_DIR}/cpuSw_dataManager_dataManager test
	make -C ${CRATES_DIR}/cpuSw_dataAnalysis_dataAnalysis test
	make -C ${CRATES_DIR}/cpuSw_decryptor_decryptor test
	make -C ${CRATES_DIR}/cpuSw_encryptor_encryptor test
	make -C ${CRATES_DIR}/cpuSw_logMonitor_logMonitor test
	make -C ${CRATES_DIR}/cpuSw_reportMonitor_reportMonitor test
	make -C ${CRATES_DIR}/cpuSw_firewall_firewall test
	make -C ${CRATES_DIR}/cpuSw_wifiDriver_wifiDriver_wifiDriver test

clean:: 
	make -C ${CRATES_DIR}/cpuSw_btDriver_btDriver clean
	make -C ${CRATES_DIR}/cpuSw_usbDriver_usbDriver clean
	make -C ${CRATES_DIR}/cpuSw_dataManager_dataManager clean
	make -C ${CRATES_DIR}/cpuSw_dataAnalysis_dataAnalysis clean
	make -C ${CRATES_DIR}/cpuSw_decryptor_decryptor clean
	make -C ${CRATES_DIR}/cpuSw_encryptor_encryptor clean
	make -C ${CRATES_DIR}/cpuSw_logMonitor_logMonitor clean
	make -C ${CRATES_DIR}/cpuSw_reportMonitor_reportMonitor clean
	make -C ${CRATES_DIR}/cpuSw_firewall_firewall clean
	make -C ${CRATES_DIR}/cpuSw_wifiDriver_wifiDriver_wifiDriver clean

clean:: 
	rm -rf ${TOP_DIR}/components/cpuSw_wifiDriver_wifiDriverVM_wifiDriver/build

verus: 
	make -C ${CRATES_DIR}/cpuSw_btDriver_btDriver verus
	make -C ${CRATES_DIR}/cpuSw_usbDriver_usbDriver verus
	make -C ${CRATES_DIR}/cpuSw_dataManager_dataManager verus
	make -C ${CRATES_DIR}/cpuSw_dataAnalysis_dataAnalysis verus
	make -C ${CRATES_DIR}/cpuSw_decryptor_decryptor verus
	make -C ${CRATES_DIR}/cpuSw_encryptor_encryptor verus
	make -C ${CRATES_DIR}/cpuSw_logMonitor_logMonitor verus
	make -C ${CRATES_DIR}/cpuSw_reportMonitor_reportMonitor verus
	make -C ${CRATES_DIR}/cpuSw_firewall_firewall verus
	make -C ${CRATES_DIR}/cpuSw_wifiDriver_wifiDriver_wifiDriver verus
