// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Property logmonitor_send_alert -- non-disabling VCs, part of the independence proof,
//! for every MHIP transition pair (per direction whose firing member is a
//! component): pre-assertions preservation (the firing does not disable another
//! transition -- its pre-assertions still hold) and post-assertions preservation
//! (the firing preserves another transition's established post-assertions).
//! Together with the property-independent Commutativity VCs, these establish
//! that concurrently-enabled transitions do not interfere.
//! Each proof fn has an empty body: Verus discharges `requires ==> ensures`
//! via SMT; add proof hints in the body if a VC does not discharge.

#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unused_imports)]

use vstd::prelude::*;

use crate::assertions::*;
use crate::logmonitor_send_alert::assertions::*;
use crate::system_state::SystemState;
use crate::write_frames::*;

verus! {


} // verus!
