// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_wifiRecv: Option<Common::IncomingWifiMessage_Impl>,
  pub api_analysis_report: Option<Common::OutgoingWifiMessage_Impl>,
  pub api_alert_in: Option<u8>,
}

/// container for component's incoming port values and GUMBO state variables
pub struct PreStateContainer_wGSV {
  pub In_alert_cmd: bool,
  pub api_wifiRecv: Option<Common::IncomingWifiMessage_Impl>,
  pub api_analysis_report: Option<Common::OutgoingWifiMessage_Impl>,
  pub api_alert_in: Option<u8>,
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_wifiRecv(container.api_wifiRecv);
  put_analysis_report(container.api_analysis_report);
  put_alert_in(container.api_alert_in);
}

/// setter for component's incoming port values and GUMBO state variables
pub fn put_concrete_inputs_container_wGSV(container: PreStateContainer_wGSV)
{
  put_alert_cmd(container.In_alert_cmd);
  put_wifiRecv(container.api_wifiRecv);
  put_analysis_report(container.api_analysis_report);
  put_alert_in(container.api_alert_in);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(
  wifiRecv: Option<Common::IncomingWifiMessage_Impl>,
  analysis_report: Option<Common::OutgoingWifiMessage_Impl>,
  alert_in: Option<u8>)
{
  put_wifiRecv(wifiRecv);
  put_analysis_report(analysis_report);
  put_alert_in(alert_in);
}

/// setter for component's incoming port values and GUMBO state variables
pub fn put_concrete_inputs_wGSV(
  In_alert_cmd: bool,
  wifiRecv: Option<Common::IncomingWifiMessage_Impl>,
  analysis_report: Option<Common::OutgoingWifiMessage_Impl>,
  alert_in: Option<u8>)
{
  put_alert_cmd(In_alert_cmd);
  put_wifiRecv(wifiRecv);
  put_analysis_report(analysis_report);
  put_alert_in(alert_in);
}

/// setter for IN EventDataPort
pub fn put_wifiRecv(value: Option<Common::IncomingWifiMessage_Impl>)
{
  *extern_api::IN_wifiRecv.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// getter for OUT EventDataPort
pub fn get_wifiSend() -> Option<Common::OutgoingWifiMessage_Impl>
{
  return extern_api::OUT_wifiSend.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// getter for OUT EventDataPort
pub fn get_HMD_log() -> Option<Common::EncryptedMessage_Impl>
{
  return extern_api::OUT_HMD_log.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// setter for IN EventDataPort
pub fn put_analysis_report(value: Option<Common::OutgoingWifiMessage_Impl>)
{
  *extern_api::IN_analysis_report.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// getter for OUT EventDataPort
pub fn get_analysis_request() -> Option<Common::AnalysisRequest_Impl>
{
  return extern_api::OUT_analysis_request.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// setter for IN EventPort
pub fn put_alert_in(value: Option<u8>)
{
  *extern_api::IN_alert_in.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// getter for GUMBO State Variable
pub fn get_alert_cmd() -> bool
{
  unsafe {
    match &crate::app {
      Some(inner) => inner.alert_cmd,
      None => panic!("The app is None")
    }
  }
}

/// setter for GUMBO State Variable
pub fn put_alert_cmd(value: bool)
{
  unsafe {
    match &mut crate::app {
      Some(inner) => inner.alert_cmd = value,
      None => panic!("The app is None")
    }
  }
}
