// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {
  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct WifiHeader_Impl {
    pub Host: shortText,
    pub UserAgent: shortText,
    pub ContentLength: u32,
    pub XForwardedProto: shortText,
    pub XForwardedFor: ip_address,
    pub XRealIP: ip_address
  }

  impl Default for WifiHeader_Impl {
    fn default() -> Self
    {
      Self { Host: [0; Common::Common_shortText_DIM_0], UserAgent: [0; Common::Common_shortText_DIM_0], ContentLength: 0, XForwardedProto: [0; Common::Common_shortText_DIM_0], XForwardedFor: [0; Common::Common_ip_address_DIM_0], XRealIP: [0; Common::Common_ip_address_DIM_0] }
    }
  }
}