// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {
  pub trait cpuSw_wifiDriver_wifiDriver_wifiDriver_Api {}

  pub trait cpuSw_wifiDriver_wifiDriver_wifiDriver_Put_Api: cpuSw_wifiDriver_wifiDriver_wifiDriver_Api {
    #[verifier::external_body]
    fn unverified_put_wifiSend(
      &mut self,
      value: Common::DummyMessage_Impl)
    {
      extern_api::unsafe_put_wifiSend(&value);
    }

    #[verifier::external_body]
    fn unverified_put_HMD_log(
      &mut self,
      value: Common::encryptedPayload_Impl)
    {
      extern_api::unsafe_put_HMD_log(&value);
    }

    #[verifier::external_body]
    fn unverified_put_analysis_request(
      &mut self,
      value: Common::AnalysisRequest_Impl)
    {
      extern_api::unsafe_put_analysis_request(&value);
    }
  }

  pub trait cpuSw_wifiDriver_wifiDriver_wifiDriver_Get_Api: cpuSw_wifiDriver_wifiDriver_wifiDriver_Api {
    #[verifier::external_body]
    fn unverified_get_wifiRecv(
      &mut self,
      value: &Ghost<Option<Common::IncomingWifiMessage_Impl>>) -> (res : Option<Common::IncomingWifiMessage_Impl>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_wifiRecv();
    }

    #[verifier::external_body]
    fn unverified_get_analysis_report(
      &mut self,
      value: &Ghost<Option<Common::AnalysisReport_Impl>>) -> (res : Option<Common::AnalysisReport_Impl>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_analysis_report();
    }

    #[verifier::external_body]
    fn unverified_get_alert(
      &mut self,
      value: &Ghost<Option<Common::DummyMessage_Impl>>) -> (res : Option<Common::DummyMessage_Impl>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_alert();
    }
  }

  pub trait cpuSw_wifiDriver_wifiDriver_wifiDriver_Full_Api: cpuSw_wifiDriver_wifiDriver_wifiDriver_Put_Api + cpuSw_wifiDriver_wifiDriver_wifiDriver_Get_Api {}

  pub struct cpuSw_wifiDriver_wifiDriver_wifiDriver_Application_Api<API: cpuSw_wifiDriver_wifiDriver_wifiDriver_Api> {
    pub api: API,

    pub ghost wifiRecv: Option<Common::IncomingWifiMessage_Impl>,
    pub ghost analysis_report: Option<Common::AnalysisReport_Impl>,
    pub ghost alert: Option<Common::DummyMessage_Impl>,
    pub ghost wifiSend: Option<Common::DummyMessage_Impl>,
    pub ghost HMD_log: Option<Common::encryptedPayload_Impl>,
    pub ghost analysis_request: Option<Common::AnalysisRequest_Impl>
  }

  impl<API: cpuSw_wifiDriver_wifiDriver_wifiDriver_Put_Api> cpuSw_wifiDriver_wifiDriver_wifiDriver_Application_Api<API> {
    pub fn put_wifiSend(
      &mut self,
      value: Common::DummyMessage_Impl)
      ensures
        old(self).wifiRecv == self.wifiRecv,
        self.wifiSend == Some(value),
        old(self).HMD_log == self.HMD_log,
        old(self).analysis_report == self.analysis_report,
        old(self).analysis_request == self.analysis_request,
        old(self).alert == self.alert,
    {
      self.api.unverified_put_wifiSend(value);
      self.wifiSend = Some(value);
    }
    pub fn put_HMD_log(
      &mut self,
      value: Common::encryptedPayload_Impl)
      ensures
        old(self).wifiRecv == self.wifiRecv,
        old(self).wifiSend == self.wifiSend,
        self.HMD_log == Some(value),
        old(self).analysis_report == self.analysis_report,
        old(self).analysis_request == self.analysis_request,
        old(self).alert == self.alert,
    {
      self.api.unverified_put_HMD_log(value);
      self.HMD_log = Some(value);
    }
    pub fn put_analysis_request(
      &mut self,
      value: Common::AnalysisRequest_Impl)
      ensures
        old(self).wifiRecv == self.wifiRecv,
        old(self).wifiSend == self.wifiSend,
        old(self).HMD_log == self.HMD_log,
        old(self).analysis_report == self.analysis_report,
        self.analysis_request == Some(value),
        old(self).alert == self.alert,
    {
      self.api.unverified_put_analysis_request(value);
      self.analysis_request = Some(value);
    }
  }

  impl<API: cpuSw_wifiDriver_wifiDriver_wifiDriver_Get_Api> cpuSw_wifiDriver_wifiDriver_wifiDriver_Application_Api<API> {
    pub fn get_wifiRecv(&mut self) -> (res : Option<Common::IncomingWifiMessage_Impl>)
      ensures
        old(self).wifiRecv == self.wifiRecv,
        res == self.wifiRecv,
        old(self).wifiSend == self.wifiSend,
        old(self).HMD_log == self.HMD_log,
        old(self).analysis_report == self.analysis_report,
        old(self).analysis_request == self.analysis_request,
        old(self).alert == self.alert,
    {
      self.api.unverified_get_wifiRecv(&Ghost(self.wifiRecv))
    }
    pub fn get_analysis_report(&mut self) -> (res : Option<Common::AnalysisReport_Impl>)
      ensures
        old(self).wifiRecv == self.wifiRecv,
        old(self).wifiSend == self.wifiSend,
        old(self).HMD_log == self.HMD_log,
        old(self).analysis_report == self.analysis_report,
        res == self.analysis_report,
        old(self).analysis_request == self.analysis_request,
        old(self).alert == self.alert,
    {
      self.api.unverified_get_analysis_report(&Ghost(self.analysis_report))
    }
    pub fn get_alert(&mut self) -> (res : Option<Common::DummyMessage_Impl>)
      ensures
        old(self).wifiRecv == self.wifiRecv,
        old(self).wifiSend == self.wifiSend,
        old(self).HMD_log == self.HMD_log,
        old(self).analysis_report == self.analysis_report,
        old(self).analysis_request == self.analysis_request,
        old(self).alert == self.alert,
        res == self.alert,
    {
      self.api.unverified_get_alert(&Ghost(self.alert))
    }
  }

  pub struct cpuSw_wifiDriver_wifiDriver_wifiDriver_Initialization_Api;
  impl cpuSw_wifiDriver_wifiDriver_wifiDriver_Api for cpuSw_wifiDriver_wifiDriver_wifiDriver_Initialization_Api {}
  impl cpuSw_wifiDriver_wifiDriver_wifiDriver_Put_Api for cpuSw_wifiDriver_wifiDriver_wifiDriver_Initialization_Api {}

  pub const fn init_api() -> cpuSw_wifiDriver_wifiDriver_wifiDriver_Application_Api<cpuSw_wifiDriver_wifiDriver_wifiDriver_Initialization_Api> {
    return cpuSw_wifiDriver_wifiDriver_wifiDriver_Application_Api {
      api: cpuSw_wifiDriver_wifiDriver_wifiDriver_Initialization_Api {},

      wifiRecv: None,
      analysis_report: None,
      alert: None,
      wifiSend: None,
      HMD_log: None,
      analysis_request: None
    }
  }

  pub struct cpuSw_wifiDriver_wifiDriver_wifiDriver_Compute_Api;
  impl cpuSw_wifiDriver_wifiDriver_wifiDriver_Api for cpuSw_wifiDriver_wifiDriver_wifiDriver_Compute_Api {}
  impl cpuSw_wifiDriver_wifiDriver_wifiDriver_Put_Api for cpuSw_wifiDriver_wifiDriver_wifiDriver_Compute_Api {}
  impl cpuSw_wifiDriver_wifiDriver_wifiDriver_Get_Api for cpuSw_wifiDriver_wifiDriver_wifiDriver_Compute_Api {}
  impl cpuSw_wifiDriver_wifiDriver_wifiDriver_Full_Api for cpuSw_wifiDriver_wifiDriver_wifiDriver_Compute_Api {}

  pub const fn compute_api() -> cpuSw_wifiDriver_wifiDriver_wifiDriver_Application_Api<cpuSw_wifiDriver_wifiDriver_wifiDriver_Compute_Api> {
    return cpuSw_wifiDriver_wifiDriver_wifiDriver_Application_Api {
      api: cpuSw_wifiDriver_wifiDriver_wifiDriver_Compute_Api {},

      wifiRecv: None,
      analysis_report: None,
      alert: None,
      wifiSend: None,
      HMD_log: None,
      analysis_request: None
    }
  }
}